In [1]:
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report
import sklearn.metrics as metrics
from sklearn.preprocessing import StandardScaler
from sklearn import svm
import numpy as np
import matplotlib.pyplot as plt
import glob

In [2]:
df_train = pd.concat([pd.read_csv(f, nrows= int(len(open(f).readlines())/2)) for f in glob.glob('interactions-UID_*.csv')], ignore_index = True, sort=False)
df_test = pd.concat([pd.read_csv(f, skiprows=range(1,int(len(open(f).readlines())/2))) for f in glob.glob('interactions-UID_*.csv')], ignore_index = True, sort=False)

In [3]:
len(df_train)

10589

In [4]:
len(df_test)

10610

In [5]:
def stanD(df):
    df = df.replace(to_replace = np.nan, 
                 value = 0)
    df[df==np.inf]=np.nan
    df.fillna(df.mean(), inplace=True)
    features = ['interStrokeTime','strokeDuration','startX','startY','stopX','stopY','distanceEndToEnd','meanResultantLength','UDLRflag','directionEndToEnd','20pcPairwiseVelocity','50pcPairwiseVelocity','80pcPairwiseVelocity','20pcPairwiseAccel','50pcPairwiseAccel','80pcPairwiseAccel','medianVelocityLast3Points','largestDeviationEndToEnd','20pcDeviationEndToEnd','50pcDeviationEndToEnd','80pcDeviationEndToEnd','averageDirection','trajectoryLength','distE2EandtrajLength','averageVelocity','medianAccellerationAtFirst5points','midStrokePressure','midStrokeAreaCovered','midStrokeFingerOrientation','changeFingerOrientation','phoneOrientation','docID','phoneID']
    x = df.loc[:, features].values
    y = df.loc[:,['userID']].values
    x_scaled = StandardScaler().fit_transform(x)
    x_value = pd.DataFrame(data = x_scaled, columns = features)
    return x_value,y

In [6]:
# test one 
#df_test = df_test[df_test['userID'] == 34]


# split train dataset into X and y
trainSplit = stanD(df_train)

# split test dataset into X and y
testSplit = stanD(df_test)

#SVM 
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(trainSplit[0], trainSplit[1])
y_pred = clf.predict(testSplit[0])



#testcount = testcount + 1

C:\Users\rccg-\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
#print accuracy_score for each value of user_ID
print("Accuracy:",metrics.accuracy_score(testSplit[1], y_pred))

#print confusion matrix for each value of user_ID
print(confusion_matrix(testSplit[1], y_pred))

#print classification report for each value of user_ID
print(classification_report(testSplit[1], y_pred))

Accuracy: 0.5599434495758718
[[ 95   0   0 ...   0   0   0]
 [  4 506   0 ...   9   1   0]
 [  0   0 160 ...   0   0   0]
 ...
 [  0   6   0 ...  50   0   0]
 [  0   0   0 ...   0 128   0]
 [  0   1   0 ...   0   0  61]]
              precision    recall  f1-score   support

           1       0.58      0.47      0.52       201
           2       0.65      0.82      0.72       616
           3       0.37      0.42      0.40       380
           4       0.46      0.26      0.34       121
           5       0.46      0.37      0.41       207
           6       0.82      0.54      0.65       282
           7       0.45      0.59      0.51       296
           8       0.50      0.82      0.62       310
           9       0.73      0.83      0.78       227
          10       0.46      0.39      0.42       194
          11       0.49      0.65      0.56       223
          12       0.74      0.44      0.55       172
          13       0.65      0.23      0.34       153
          14       0.5

In [8]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(testSplit[1], y_pred)
matrix.diagonal()/matrix.sum()

array([0.00895382, 0.04769086, 0.01508011, 0.00301602, 0.00716305,
       0.01423186, 0.01639962, 0.02403393, 0.01781338, 0.00716305,
       0.0137606 , 0.0070688 , 0.00329877, 0.02186616, 0.02148916,
       0.00819981, 0.02912347, 0.01526861, 0.01008483, 0.01196984,
       0.01649387, 0.00867107, 0.0401508 , 0.0063148 , 0.00584354,
       0.00348728, 0.0061263 , 0.01083883, 0.01413761, 0.00329877,
       0.00367578, 0.01102733, 0.0260132 , 0.02139491, 0.02997172,
       0.00565504, 0.01131008, 0.00933082, 0.00471254, 0.01206409,
       0.00574929])