In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import glob

In [2]:
df = pd.concat([pd.read_csv(f) for f in glob.glob('interactions-UID_*.csv')], ignore_index = True)

In [3]:
df = df.replace(to_replace = np.nan, 
                 value = 0)
df[df==np.inf]=np.nan
df.fillna(df.mean(), inplace=True)

In [4]:
features = ['interStrokeTime','strokeDuration','startX','startY','stopX','stopY','distanceEndToEnd','meanResultantLength','UDLRflag','directionEndToEnd','20pcPairwiseVelocity','50pcPairwiseVelocity','80pcPairwiseVelocity','20pcPairwiseAccel','50pcPairwiseAccel','80pcPairwiseAccel','medianVelocityLast3Points','largestDeviationEndToEnd','20pcDeviationEndToEnd','50pcDeviationEndToEnd','80pcDeviationEndToEnd','averageDirection','trajectoryLength','distE2EandtrajLength','averageVelocity','medianAccellerationAtFirst5points','midStrokePressure','midStrokeAreaCovered','midStrokeFingerOrientation','changeFingerOrientation','phoneOrientation','docID','phoneID']
x = df.loc[:, features].values

In [5]:
y = df.loc[:,['userID']].values

In [6]:
x_scaled = StandardScaler().fit_transform(x)

In [7]:
pd.DataFrame(data = x_scaled, columns = features)

interStrokeTime  strokeDuration    startX    startY     stopX  \
0            -0.000169       -0.423700  0.955605  0.126532 -1.283096   
1             0.000155       -0.559132  0.932894  0.631638 -1.410321   
2            -0.000174       -0.463048 -1.417951 -0.414763  1.494547   
3            -0.000162       -0.487756 -1.565594 -0.065889  1.505147   
4            -0.000182       -0.477690  1.296376  0.836196 -1.484524   
...                ...             ...       ...       ...       ...   
21153         0.000424        1.203308 -0.747933 -0.847712 -1.049857   
21154         0.001133        0.601187 -1.406595  0.980513 -1.537536   
21155         0.000501        1.307627 -1.486094 -0.727448 -1.622350   
21156         0.000303        0.576480 -1.508805 -0.571106 -1.579948   
21157        -0.000199       -0.299249 -1.327096 -1.292796 -1.760173   

          stopY  distanceEndToEnd  meanResultantLength  UDLRflag  \
0     -0.479598          0.986518             0.337695  1.417415   
1     -0.479598          1.206494             0.030156  1.417415   
2     -0.070042          2.064413             0.797119 -1.086001   
3      0.129485          2.217303             1.019343 -1.086001   
4     -0.605615          1.829362            -0.798730  1.417415   
...         ...               ...                  ...       ...   
21153  2.020032          2.480747             0.966383  0.165707   
21154  3.269828          2.017428             1.026994  0.165707   
21155  2.503127          2.961654             0.988791  0.165707   
21156  2.608151          2.916930             1.048146  0.165707   
21157 -0.164555          0.218173             0.761648  0.165707   

       directionEndToEnd  ...  distE2EandtrajLength  averageVelocity  \
0              -2.063726  ...              0.387059         0.046811   
1              -1.950336  ...              0.270127         0.950036   
2              -0.078725  ...              0.295646         0.591067   
3              -0.105823  ...              0.418564         0.767478   
4              -1.907970  ...             -0.181878         0.725189   
...                  ...  ...                   ...              ...   
21153           0.746666  ...              0.398758        -0.609106   
21154           0.727699  ...              0.384665        -0.548450   
21155           0.722145  ...              0.276874        -0.592953   
21156           0.712100  ...              0.385916        -0.480135   
21157           0.877604  ...              0.451647        -0.381640   

       medianAccellerationAtFirst5points  midStrokePressure  \
0                              -0.039082           0.996462   
1                              -0.037485           1.097627   
2                              -0.030804           1.047044   
3                              -0.045908           1.654034   
4                              -0.033992           1.299957   
...                                  ...                ...   
21153                          -0.040133           0.945879   
21154                          -0.040395           1.805782   
21155                          -0.041056           0.945879   
21156                          -0.040325           0.642384   
21157                          -0.041037           0.743549   

       midStrokeAreaCovered  midStrokeFingerOrientation  \
0                  1.577443                    -0.10869   
1                  2.394702                    -0.10869   
2                  2.394702                    -0.10869   
3                  2.803331                    -0.10869   
4                  3.620774                    -0.10869   
...                     ...                         ...   
21153              1.577443                    -0.10869   
21154              1.986072                    -0.10869   
21155              0.760000                    -0.10869   
21156              0.351371                    -0.10869   
21157              0.555685                    -0.1086

In [8]:
train_pct_index = int(0.8 * len(x_scaled))
X_train, X_test = x_scaled[:train_pct_index], x_scaled[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

In [50]:
pca = PCA().fit(x_scaled)

In [51]:
pca = PCA(n_components=20)
x_reduced = pca.fit_transform(x_scaled)
principalDf = pd.DataFrame(data = x_reduced
             , columns = ['principal component 1', 'principal component 2','principal component 3', 'principal component 4','principal component 5', 'principal component 6','principal component 7', 'principal component 8','principal component 9', 'principal component 10','principal component 11', 'principal component 12','principal component 13', 'principal component 14','principal component 15', 'principal component 16','principal component 17', 'principal component 18','principal component 19', 'principal component 20'])

principalDf.head(20)

principal component 1  principal component 2  principal component 3  \
0                2.082493              -1.615634              -1.056804   
1                4.189172              -2.532083              -1.423491   
2                0.797883               3.472874              -1.304161   
3                1.147363               2.254397              -1.226318   
4                3.007121              -5.021063              -0.859257   
5                2.923549              -1.437473              -1.233940   
6               -2.039038              -1.220264               0.922956   
7                2.538580               2.188764              -1.693398   
8                2.673820               2.364311               0.190695   
9                3.701708              -2.990826              -1.526485   
10               3.353494              -2.809792              -1.296081   
11               0.904782               4.434108              -1.383844   
12               1.507767               1.737576              -1.188967   
13               3.524671              -2.614367              -1.410374   
14               3.334049              -1.560296              -0.585394   
15              -0.251978               0.386408              -0.453141   
16               1.449760               2.180677              -1.248510   
17               3.519155              -3.683041              -1.200776   
18               2.233944              -1.784626              -1.076362   
19               0.483819              -1.352689              -0.227306   

    principal component 4  principal component 5  principal component 6  \
0                0.379364               0.132815               1.562285   
1                0.924696               0.921155               0.504413   
2                0.834214               2.140160              -0.669098   
3                0.884979               2.340981              -1.440460   
4                1.077232               2.160451               1.066666   
5                1.013593              -0.202836               1.026728   
6                1.269650              -1.903640              -0.238764   
7                0.725202               1.829510              -1.961893   
8                0.333421               1.292025              -1.656785   
9                1.083952               1.642556               1.054900   
10               0.538687               0.360493               0.640534   
11               0.706111               1.576685              -0.425944   
12               0.646349               1.765811              -1.963730   
13               1.109262               1.105748               1.213843   
14               0.493465              -0.546843               1.231780   
15              -0.422919               1.422003              -1.370480   
16               0.117228               1.642684              -1.730425   
17               0.503079               1.543652               1.258128   
18               0.108606              -0.393742               1.251924   
19               0.186324              -2.261368               1.691234   

    principal component 7  principal component 8  principal component 9  \
0               -0.886825              -0.205907              -1.459704   
1               -0.523819               0.388297              -1.471504   
2               -1.109345              -0.921439               0.377234   
3               -1.438959              -0.862135               0.191028   
4               -0.382093               0.089912              -1.336387   
5               -0.846538               0.231667              -1.434284   
6               -0.415345              -2.516536               2.533555   
7               -0.940435              -0.674526               0.176185   
8               -0.873304              -0.108206               0.925864   
9                0.011326               0.150335              -1.797425   
10              -0.772156  

In [52]:
df[['userID']].head()

userID
0       1
1       1
2       1
3       1
4       1

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_reduced, y, test_size=0.3, random_state=109)

In [62]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

C:\Users\kieni\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [67]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[ 81   1   0 ...   0   0   1]
 [  2 317   0 ...   5   0   0]
 [  0   0  59 ...   0   0   0]
 ...
 [  2  12   0 ...  42   0   0]
 [  0   0   0 ...   0  59   0]
 [  1   1   0 ...   0   0  33]]
              precision    recall  f1-score   support

           1       0.63      0.68      0.65       120
           2       0.68      0.85      0.75       373
           3       0.32      0.25      0.28       234
           4       0.65      0.49      0.56        79
           5       0.45      0.42      0.43       125
           6       0.70      0.75      0.72       161
           7       0.49      0.57      0.53       162
           8       0.63      0.70      0.66       191
           9       0.78      0.83      0.81       125
          10       0.51      0.54      0.53       134
          11       0.47      0.65      0.55       125
          12       0.67      0.70      0.69       111
          13       0.33      0.20      0.25        79
          14       0.63      0.89      0.74       1