In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import glob

In [2]:
df = pd.concat([pd.read_csv(f) for f in glob.glob('interactions-UID_*.csv')], ignore_index = True)

In [3]:
df = df.replace(to_replace = np.nan, 
                 value = 0)
df[df==np.inf]=np.nan
df.fillna(df.mean(), inplace=True)

In [4]:
features = ['interStrokeTime','strokeDuration','startX','startY','stopX','stopY','distanceEndToEnd','meanResultantLength','UDLRflag','directionEndToEnd','20pcPairwiseVelocity','50pcPairwiseVelocity','80pcPairwiseVelocity','20pcPairwiseAccel','50pcPairwiseAccel','80pcPairwiseAccel','medianVelocityLast3Points','largestDeviationEndToEnd','20pcDeviationEndToEnd','50pcDeviationEndToEnd','80pcDeviationEndToEnd','averageDirection','trajectoryLength','distE2EandtrajLength','averageVelocity','medianAccellerationAtFirst5points','midStrokePressure','midStrokeAreaCovered','midStrokeFingerOrientation','changeFingerOrientation','phoneOrientation','docID','phoneID']
x = df.loc[:, features].values

In [5]:
y = df.loc[:,['userID']].values

In [6]:
x_scaled = StandardScaler().fit_transform(x)

In [7]:
pd.DataFrame(data = x_scaled, columns = features)

interStrokeTime  strokeDuration    startX    startY     stopX  \
0            -0.000169       -0.423700  0.955605  0.126532 -1.283096   
1             0.000155       -0.559132  0.932894  0.631638 -1.410321   
2            -0.000174       -0.463048 -1.417951 -0.414763  1.494547   
3            -0.000162       -0.487756 -1.565594 -0.065889  1.505147   
4            -0.000182       -0.477690  1.296376  0.836196 -1.484524   
...                ...             ...       ...       ...       ...   
21153         0.000424        1.203308 -0.747933 -0.847712 -1.049857   
21154         0.001133        0.601187 -1.406595  0.980513 -1.537536   
21155         0.000501        1.307627 -1.486094 -0.727448 -1.622350   
21156         0.000303        0.576480 -1.508805 -0.571106 -1.579948   
21157        -0.000199       -0.299249 -1.327096 -1.292796 -1.760173   

          stopY  distanceEndToEnd  meanResultantLength  UDLRflag  \
0     -0.479598          0.986518             0.337695  1.417415   
1     -0.479598          1.206494             0.030156  1.417415   
2     -0.070042          2.064413             0.797119 -1.086001   
3      0.129485          2.217303             1.019343 -1.086001   
4     -0.605615          1.829362            -0.798730  1.417415   
...         ...               ...                  ...       ...   
21153  2.020032          2.480747             0.966383  0.165707   
21154  3.269828          2.017428             1.026994  0.165707   
21155  2.503127          2.961654             0.988791  0.165707   
21156  2.608151          2.916930             1.048146  0.165707   
21157 -0.164555          0.218173             0.761648  0.165707   

       directionEndToEnd  ...  distE2EandtrajLength  averageVelocity  \
0              -2.063726  ...              0.387059         0.046811   
1              -1.950336  ...              0.270127         0.950036   
2              -0.078725  ...              0.295646         0.591067   
3              -0.105823  ...              0.418564         0.767478   
4              -1.907970  ...             -0.181878         0.725189   
...                  ...  ...                   ...              ...   
21153           0.746666  ...              0.398758        -0.609106   
21154           0.727699  ...              0.384665        -0.548450   
21155           0.722145  ...              0.276874        -0.592953   
21156           0.712100  ...              0.385916        -0.480135   
21157           0.877604  ...              0.451647        -0.381640   

       medianAccellerationAtFirst5points  midStrokePressure  \
0                              -0.039082           0.996462   
1                              -0.037485           1.097627   
2                              -0.030804           1.047044   
3                              -0.045908           1.654034   
4                              -0.033992           1.299957   
...                                  ...                ...   
21153                          -0.040133           0.945879   
21154                          -0.040395           1.805782   
21155                          -0.041056           0.945879   
21156                          -0.040325           0.642384   
21157                          -0.041037           0.743549   

       midStrokeAreaCovered  midStrokeFingerOrientation  \
0                  1.577443                    -0.10869   
1                  2.394702                    -0.10869   
2                  2.394702                    -0.10869   
3                  2.803331                    -0.10869   
4                  3.620774                    -0.10869   
...                     ...                         ...   
21153              1.577443                    -0.10869   
21154              1.986072                    -0.10869   
21155              0.760000                    -0.10869   
21156              0.351371                    -0.10869   
21157              0.555685                    -0.1086

(16926, 1)

In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 1 36  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [11  6  0 ...  0  0  0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          16       0.00      0.00

C:\Users\kieni\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kieni\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


NameError: name 'metrics' is not defined