In [7]:
import glob
import numpy as np
import pandas as pd
from sklearn.model_selection import LeaveOneOut

In [9]:
df = pd.read_csv('touchscreen-data.csv')
loo = LeaveOneOut()
for train, test in loo.split(df):
    print("%s %s" % (train, test))

[    1     2     3 ... 21155 21156 21157] [0]
[    0     2     3 ... 21155 21156 21157] [1]
[    0     1     3 ... 21155 21156 21157] [2]
[    0     1     2 ... 21155 21156 21157] [3]
[    0     1     2 ... 21155 21156 21157] [4]
[    0     1     2 ... 21155 21156 21157] [5]
[    0     1     2 ... 21155 21156 21157] [6]
[    0     1     2 ... 21155 21156 21157] [7]
[    0     1     2 ... 21155 21156 21157] [8]
[    0     1     2 ... 21155 21156 21157] [9]
[    0     1     2 ... 21155 21156 21157] [10]
[    0     1     2 ... 21155 21156 21157] [11]
[    0     1     2 ... 21155 21156 21157] [12]
[    0     1     2 ... 21155 21156 21157] [13]
[    0     1     2 ... 21155 21156 21157] [14]
[    0     1     2 ... 21155 21156 21157] [15]
[    0     1     2 ... 21155 21156 21157] [16]
[    0     1     2 ... 21155 21156 21157] [17]
[    0     1     2 ... 21155 21156 21157] [18]
[    0     1     2 ... 21155 21156 21157] [19]
[    0     1     2 ... 21155 21156 21157] [20]
[    0     1     2 ... 

[    0     1     2 ... 21155 21156 21157] [182]
[    0     1     2 ... 21155 21156 21157] [183]
[    0     1     2 ... 21155 21156 21157] [184]
[    0     1     2 ... 21155 21156 21157] [185]
[    0     1     2 ... 21155 21156 21157] [186]
[    0     1     2 ... 21155 21156 21157] [187]
[    0     1     2 ... 21155 21156 21157] [188]
[    0     1     2 ... 21155 21156 21157] [189]
[    0     1     2 ... 21155 21156 21157] [190]
[    0     1     2 ... 21155 21156 21157] [191]
[    0     1     2 ... 21155 21156 21157] [192]
[    0     1     2 ... 21155 21156 21157] [193]
[    0     1     2 ... 21155 21156 21157] [194]
[    0     1     2 ... 21155 21156 21157] [195]
[    0     1     2 ... 21155 21156 21157] [196]
[    0     1     2 ... 21155 21156 21157] [197]
[    0     1     2 ... 21155 21156 21157] [198]
[    0     1     2 ... 21155 21156 21157] [199]
[    0     1     2 ... 21155 21156 21157] [200]
[    0     1     2 ... 21155 21156 21157] [201]
[    0     1     2 ... 21155 21156 21157

[    0     1     2 ... 21155 21156 21157] [367]
[    0     1     2 ... 21155 21156 21157] [368]
[    0     1     2 ... 21155 21156 21157] [369]
[    0     1     2 ... 21155 21156 21157] [370]
[    0     1     2 ... 21155 21156 21157] [371]
[    0     1     2 ... 21155 21156 21157] [372]
[    0     1     2 ... 21155 21156 21157] [373]
[    0     1     2 ... 21155 21156 21157] [374]
[    0     1     2 ... 21155 21156 21157] [375]
[    0     1     2 ... 21155 21156 21157] [376]
[    0     1     2 ... 21155 21156 21157] [377]
[    0     1     2 ... 21155 21156 21157] [378]
[    0     1     2 ... 21155 21156 21157] [379]
[    0     1     2 ... 21155 21156 21157] [380]
[    0     1     2 ... 21155 21156 21157] [381]
[    0     1     2 ... 21155 21156 21157] [382]
[    0     1     2 ... 21155 21156 21157] [383]
[    0     1     2 ... 21155 21156 21157] [384]
[    0     1     2 ... 21155 21156 21157] [385]
[    0     1     2 ... 21155 21156 21157] [386]
[    0     1     2 ... 21155 21156 21157

[    0     1     2 ... 21155 21156 21157] [586]
[    0     1     2 ... 21155 21156 21157] [587]
[    0     1     2 ... 21155 21156 21157] [588]
[    0     1     2 ... 21155 21156 21157] [589]
[    0     1     2 ... 21155 21156 21157] [590]
[    0     1     2 ... 21155 21156 21157] [591]
[    0     1     2 ... 21155 21156 21157] [592]
[    0     1     2 ... 21155 21156 21157] [593]
[    0     1     2 ... 21155 21156 21157] [594]
[    0     1     2 ... 21155 21156 21157] [595]
[    0     1     2 ... 21155 21156 21157] [596]
[    0     1     2 ... 21155 21156 21157] [597]
[    0     1     2 ... 21155 21156 21157] [598]
[    0     1     2 ... 21155 21156 21157] [599]
[    0     1     2 ... 21155 21156 21157] [600]
[    0     1     2 ... 21155 21156 21157] [601]
[    0     1     2 ... 21155 21156 21157] [602]
[    0     1     2 ... 21155 21156 21157] [603]
[    0     1     2 ... 21155 21156 21157] [604]
[    0     1     2 ... 21155 21156 21157] [605]
[    0     1     2 ... 21155 21156 21157

[    0     1     2 ... 21155 21156 21157] [837]
[    0     1     2 ... 21155 21156 21157] [838]
[    0     1     2 ... 21155 21156 21157] [839]
[    0     1     2 ... 21155 21156 21157] [840]
[    0     1     2 ... 21155 21156 21157] [841]
[    0     1     2 ... 21155 21156 21157] [842]
[    0     1     2 ... 21155 21156 21157] [843]
[    0     1     2 ... 21155 21156 21157] [844]
[    0     1     2 ... 21155 21156 21157] [845]
[    0     1     2 ... 21155 21156 21157] [846]
[    0     1     2 ... 21155 21156 21157] [847]
[    0     1     2 ... 21155 21156 21157] [848]
[    0     1     2 ... 21155 21156 21157] [849]
[    0     1     2 ... 21155 21156 21157] [850]
[    0     1     2 ... 21155 21156 21157] [851]
[    0     1     2 ... 21155 21156 21157] [852]
[    0     1     2 ... 21155 21156 21157] [853]
[    0     1     2 ... 21155 21156 21157] [854]
[    0     1     2 ... 21155 21156 21157] [855]
[    0     1     2 ... 21155 21156 21157] [856]
[    0     1     2 ... 21155 21156 21157

[    0     1     2 ... 21155 21156 21157] [1100]
[    0     1     2 ... 21155 21156 21157] [1101]
[    0     1     2 ... 21155 21156 21157] [1102]
[    0     1     2 ... 21155 21156 21157] [1103]
[    0     1     2 ... 21155 21156 21157] [1104]
[    0     1     2 ... 21155 21156 21157] [1105]
[    0     1     2 ... 21155 21156 21157] [1106]
[    0     1     2 ... 21155 21156 21157] [1107]
[    0     1     2 ... 21155 21156 21157] [1108]
[    0     1     2 ... 21155 21156 21157] [1109]
[    0     1     2 ... 21155 21156 21157] [1110]
[    0     1     2 ... 21155 21156 21157] [1111]
[    0     1     2 ... 21155 21156 21157] [1112]
[    0     1     2 ... 21155 21156 21157] [1113]
[    0     1     2 ... 21155 21156 21157] [1114]
[    0     1     2 ... 21155 21156 21157] [1115]
[    0     1     2 ... 21155 21156 21157] [1116]
[    0     1     2 ... 21155 21156 21157] [1117]
[    0     1     2 ... 21155 21156 21157] [1118]
[    0     1     2 ... 21155 21156 21157] [1119]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [1363]
[    0     1     2 ... 21155 21156 21157] [1364]
[    0     1     2 ... 21155 21156 21157] [1365]
[    0     1     2 ... 21155 21156 21157] [1366]
[    0     1     2 ... 21155 21156 21157] [1367]
[    0     1     2 ... 21155 21156 21157] [1368]
[    0     1     2 ... 21155 21156 21157] [1369]
[    0     1     2 ... 21155 21156 21157] [1370]
[    0     1     2 ... 21155 21156 21157] [1371]
[    0     1     2 ... 21155 21156 21157] [1372]
[    0     1     2 ... 21155 21156 21157] [1373]
[    0     1     2 ... 21155 21156 21157] [1374]
[    0     1     2 ... 21155 21156 21157] [1375]
[    0     1     2 ... 21155 21156 21157] [1376]
[    0     1     2 ... 21155 21156 21157] [1377]
[    0     1     2 ... 21155 21156 21157] [1378]
[    0     1     2 ... 21155 21156 21157] [1379]
[    0     1     2 ... 21155 21156 21157] [1380]
[    0     1     2 ... 21155 21156 21157] [1381]
[    0     1     2 ... 21155 21156 21157] [1382]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [1633]
[    0     1     2 ... 21155 21156 21157] [1634]
[    0     1     2 ... 21155 21156 21157] [1635]
[    0     1     2 ... 21155 21156 21157] [1636]
[    0     1     2 ... 21155 21156 21157] [1637]
[    0     1     2 ... 21155 21156 21157] [1638]
[    0     1     2 ... 21155 21156 21157] [1639]
[    0     1     2 ... 21155 21156 21157] [1640]
[    0     1     2 ... 21155 21156 21157] [1641]
[    0     1     2 ... 21155 21156 21157] [1642]
[    0     1     2 ... 21155 21156 21157] [1643]
[    0     1     2 ... 21155 21156 21157] [1644]
[    0     1     2 ... 21155 21156 21157] [1645]
[    0     1     2 ... 21155 21156 21157] [1646]
[    0     1     2 ... 21155 21156 21157] [1647]
[    0     1     2 ... 21155 21156 21157] [1648]
[    0     1     2 ... 21155 21156 21157] [1649]
[    0     1     2 ... 21155 21156 21157] [1650]
[    0     1     2 ... 21155 21156 21157] [1651]
[    0     1     2 ... 21155 21156 21157] [1652]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [1907]
[    0     1     2 ... 21155 21156 21157] [1908]
[    0     1     2 ... 21155 21156 21157] [1909]
[    0     1     2 ... 21155 21156 21157] [1910]
[    0     1     2 ... 21155 21156 21157] [1911]
[    0     1     2 ... 21155 21156 21157] [1912]
[    0     1     2 ... 21155 21156 21157] [1913]
[    0     1     2 ... 21155 21156 21157] [1914]
[    0     1     2 ... 21155 21156 21157] [1915]
[    0     1     2 ... 21155 21156 21157] [1916]
[    0     1     2 ... 21155 21156 21157] [1917]
[    0     1     2 ... 21155 21156 21157] [1918]
[    0     1     2 ... 21155 21156 21157] [1919]
[    0     1     2 ... 21155 21156 21157] [1920]
[    0     1     2 ... 21155 21156 21157] [1921]
[    0     1     2 ... 21155 21156 21157] [1922]
[    0     1     2 ... 21155 21156 21157] [1923]
[    0     1     2 ... 21155 21156 21157] [1924]
[    0     1     2 ... 21155 21156 21157] [1925]
[    0     1     2 ... 21155 21156 21157] [1926]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [2170]
[    0     1     2 ... 21155 21156 21157] [2171]
[    0     1     2 ... 21155 21156 21157] [2172]
[    0     1     2 ... 21155 21156 21157] [2173]
[    0     1     2 ... 21155 21156 21157] [2174]
[    0     1     2 ... 21155 21156 21157] [2175]
[    0     1     2 ... 21155 21156 21157] [2176]
[    0     1     2 ... 21155 21156 21157] [2177]
[    0     1     2 ... 21155 21156 21157] [2178]
[    0     1     2 ... 21155 21156 21157] [2179]
[    0     1     2 ... 21155 21156 21157] [2180]
[    0     1     2 ... 21155 21156 21157] [2181]
[    0     1     2 ... 21155 21156 21157] [2182]
[    0     1     2 ... 21155 21156 21157] [2183]
[    0     1     2 ... 21155 21156 21157] [2184]
[    0     1     2 ... 21155 21156 21157] [2185]
[    0     1     2 ... 21155 21156 21157] [2186]
[    0     1     2 ... 21155 21156 21157] [2187]
[    0     1     2 ... 21155 21156 21157] [2188]
[    0     1     2 ... 21155 21156 21157] [2189]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [2419]
[    0     1     2 ... 21155 21156 21157] [2420]
[    0     1     2 ... 21155 21156 21157] [2421]
[    0     1     2 ... 21155 21156 21157] [2422]
[    0     1     2 ... 21155 21156 21157] [2423]
[    0     1     2 ... 21155 21156 21157] [2424]
[    0     1     2 ... 21155 21156 21157] [2425]
[    0     1     2 ... 21155 21156 21157] [2426]
[    0     1     2 ... 21155 21156 21157] [2427]
[    0     1     2 ... 21155 21156 21157] [2428]
[    0     1     2 ... 21155 21156 21157] [2429]
[    0     1     2 ... 21155 21156 21157] [2430]
[    0     1     2 ... 21155 21156 21157] [2431]
[    0     1     2 ... 21155 21156 21157] [2432]
[    0     1     2 ... 21155 21156 21157] [2433]
[    0     1     2 ... 21155 21156 21157] [2434]
[    0     1     2 ... 21155 21156 21157] [2435]
[    0     1     2 ... 21155 21156 21157] [2436]
[    0     1     2 ... 21155 21156 21157] [2437]
[    0     1     2 ... 21155 21156 21157] [2438]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [2690]
[    0     1     2 ... 21155 21156 21157] [2691]
[    0     1     2 ... 21155 21156 21157] [2692]
[    0     1     2 ... 21155 21156 21157] [2693]
[    0     1     2 ... 21155 21156 21157] [2694]
[    0     1     2 ... 21155 21156 21157] [2695]
[    0     1     2 ... 21155 21156 21157] [2696]
[    0     1     2 ... 21155 21156 21157] [2697]
[    0     1     2 ... 21155 21156 21157] [2698]
[    0     1     2 ... 21155 21156 21157] [2699]
[    0     1     2 ... 21155 21156 21157] [2700]
[    0     1     2 ... 21155 21156 21157] [2701]
[    0     1     2 ... 21155 21156 21157] [2702]
[    0     1     2 ... 21155 21156 21157] [2703]
[    0     1     2 ... 21155 21156 21157] [2704]
[    0     1     2 ... 21155 21156 21157] [2705]
[    0     1     2 ... 21155 21156 21157] [2706]
[    0     1     2 ... 21155 21156 21157] [2707]
[    0     1     2 ... 21155 21156 21157] [2708]
[    0     1     2 ... 21155 21156 21157] [2709]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [2939]
[    0     1     2 ... 21155 21156 21157] [2940]
[    0     1     2 ... 21155 21156 21157] [2941]
[    0     1     2 ... 21155 21156 21157] [2942]
[    0     1     2 ... 21155 21156 21157] [2943]
[    0     1     2 ... 21155 21156 21157] [2944]
[    0     1     2 ... 21155 21156 21157] [2945]
[    0     1     2 ... 21155 21156 21157] [2946]
[    0     1     2 ... 21155 21156 21157] [2947]
[    0     1     2 ... 21155 21156 21157] [2948]
[    0     1     2 ... 21155 21156 21157] [2949]
[    0     1     2 ... 21155 21156 21157] [2950]
[    0     1     2 ... 21155 21156 21157] [2951]
[    0     1     2 ... 21155 21156 21157] [2952]
[    0     1     2 ... 21155 21156 21157] [2953]
[    0     1     2 ... 21155 21156 21157] [2954]
[    0     1     2 ... 21155 21156 21157] [2955]
[    0     1     2 ... 21155 21156 21157] [2956]
[    0     1     2 ... 21155 21156 21157] [2957]
[    0     1     2 ... 21155 21156 21157] [2958]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [3211]
[    0     1     2 ... 21155 21156 21157] [3212]
[    0     1     2 ... 21155 21156 21157] [3213]
[    0     1     2 ... 21155 21156 21157] [3214]
[    0     1     2 ... 21155 21156 21157] [3215]
[    0     1     2 ... 21155 21156 21157] [3216]
[    0     1     2 ... 21155 21156 21157] [3217]
[    0     1     2 ... 21155 21156 21157] [3218]
[    0     1     2 ... 21155 21156 21157] [3219]
[    0     1     2 ... 21155 21156 21157] [3220]
[    0     1     2 ... 21155 21156 21157] [3221]
[    0     1     2 ... 21155 21156 21157] [3222]
[    0     1     2 ... 21155 21156 21157] [3223]
[    0     1     2 ... 21155 21156 21157] [3224]
[    0     1     2 ... 21155 21156 21157] [3225]
[    0     1     2 ... 21155 21156 21157] [3226]
[    0     1     2 ... 21155 21156 21157] [3227]
[    0     1     2 ... 21155 21156 21157] [3228]
[    0     1     2 ... 21155 21156 21157] [3229]
[    0     1     2 ... 21155 21156 21157] [3230]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [3451]
[    0     1     2 ... 21155 21156 21157] [3452]
[    0     1     2 ... 21155 21156 21157] [3453]
[    0     1     2 ... 21155 21156 21157] [3454]
[    0     1     2 ... 21155 21156 21157] [3455]
[    0     1     2 ... 21155 21156 21157] [3456]
[    0     1     2 ... 21155 21156 21157] [3457]
[    0     1     2 ... 21155 21156 21157] [3458]
[    0     1     2 ... 21155 21156 21157] [3459]
[    0     1     2 ... 21155 21156 21157] [3460]
[    0     1     2 ... 21155 21156 21157] [3461]
[    0     1     2 ... 21155 21156 21157] [3462]
[    0     1     2 ... 21155 21156 21157] [3463]
[    0     1     2 ... 21155 21156 21157] [3464]
[    0     1     2 ... 21155 21156 21157] [3465]
[    0     1     2 ... 21155 21156 21157] [3466]
[    0     1     2 ... 21155 21156 21157] [3467]
[    0     1     2 ... 21155 21156 21157] [3468]
[    0     1     2 ... 21155 21156 21157] [3469]
[    0     1     2 ... 21155 21156 21157] [3470]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [3696]
[    0     1     2 ... 21155 21156 21157] [3697]
[    0     1     2 ... 21155 21156 21157] [3698]
[    0     1     2 ... 21155 21156 21157] [3699]
[    0     1     2 ... 21155 21156 21157] [3700]
[    0     1     2 ... 21155 21156 21157] [3701]
[    0     1     2 ... 21155 21156 21157] [3702]
[    0     1     2 ... 21155 21156 21157] [3703]
[    0     1     2 ... 21155 21156 21157] [3704]
[    0     1     2 ... 21155 21156 21157] [3705]
[    0     1     2 ... 21155 21156 21157] [3706]
[    0     1     2 ... 21155 21156 21157] [3707]
[    0     1     2 ... 21155 21156 21157] [3708]
[    0     1     2 ... 21155 21156 21157] [3709]
[    0     1     2 ... 21155 21156 21157] [3710]
[    0     1     2 ... 21155 21156 21157] [3711]
[    0     1     2 ... 21155 21156 21157] [3712]
[    0     1     2 ... 21155 21156 21157] [3713]
[    0     1     2 ... 21155 21156 21157] [3714]
[    0     1     2 ... 21155 21156 21157] [3715]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [3930]
[    0     1     2 ... 21155 21156 21157] [3931]
[    0     1     2 ... 21155 21156 21157] [3932]
[    0     1     2 ... 21155 21156 21157] [3933]
[    0     1     2 ... 21155 21156 21157] [3934]
[    0     1     2 ... 21155 21156 21157] [3935]
[    0     1     2 ... 21155 21156 21157] [3936]
[    0     1     2 ... 21155 21156 21157] [3937]
[    0     1     2 ... 21155 21156 21157] [3938]
[    0     1     2 ... 21155 21156 21157] [3939]
[    0     1     2 ... 21155 21156 21157] [3940]
[    0     1     2 ... 21155 21156 21157] [3941]
[    0     1     2 ... 21155 21156 21157] [3942]
[    0     1     2 ... 21155 21156 21157] [3943]
[    0     1     2 ... 21155 21156 21157] [3944]
[    0     1     2 ... 21155 21156 21157] [3945]
[    0     1     2 ... 21155 21156 21157] [3946]
[    0     1     2 ... 21155 21156 21157] [3947]
[    0     1     2 ... 21155 21156 21157] [3948]
[    0     1     2 ... 21155 21156 21157] [3949]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [4191]
[    0     1     2 ... 21155 21156 21157] [4192]
[    0     1     2 ... 21155 21156 21157] [4193]
[    0     1     2 ... 21155 21156 21157] [4194]
[    0     1     2 ... 21155 21156 21157] [4195]
[    0     1     2 ... 21155 21156 21157] [4196]
[    0     1     2 ... 21155 21156 21157] [4197]
[    0     1     2 ... 21155 21156 21157] [4198]
[    0     1     2 ... 21155 21156 21157] [4199]
[    0     1     2 ... 21155 21156 21157] [4200]
[    0     1     2 ... 21155 21156 21157] [4201]
[    0     1     2 ... 21155 21156 21157] [4202]
[    0     1     2 ... 21155 21156 21157] [4203]
[    0     1     2 ... 21155 21156 21157] [4204]
[    0     1     2 ... 21155 21156 21157] [4205]
[    0     1     2 ... 21155 21156 21157] [4206]
[    0     1     2 ... 21155 21156 21157] [4207]
[    0     1     2 ... 21155 21156 21157] [4208]
[    0     1     2 ... 21155 21156 21157] [4209]
[    0     1     2 ... 21155 21156 21157] [4210]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [4409]
[    0     1     2 ... 21155 21156 21157] [4410]
[    0     1     2 ... 21155 21156 21157] [4411]
[    0     1     2 ... 21155 21156 21157] [4412]
[    0     1     2 ... 21155 21156 21157] [4413]
[    0     1     2 ... 21155 21156 21157] [4414]
[    0     1     2 ... 21155 21156 21157] [4415]
[    0     1     2 ... 21155 21156 21157] [4416]
[    0     1     2 ... 21155 21156 21157] [4417]
[    0     1     2 ... 21155 21156 21157] [4418]
[    0     1     2 ... 21155 21156 21157] [4419]
[    0     1     2 ... 21155 21156 21157] [4420]
[    0     1     2 ... 21155 21156 21157] [4421]
[    0     1     2 ... 21155 21156 21157] [4422]
[    0     1     2 ... 21155 21156 21157] [4423]
[    0     1     2 ... 21155 21156 21157] [4424]
[    0     1     2 ... 21155 21156 21157] [4425]
[    0     1     2 ... 21155 21156 21157] [4426]
[    0     1     2 ... 21155 21156 21157] [4427]
[    0     1     2 ... 21155 21156 21157] [4428]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [4658]
[    0     1     2 ... 21155 21156 21157] [4659]
[    0     1     2 ... 21155 21156 21157] [4660]
[    0     1     2 ... 21155 21156 21157] [4661]
[    0     1     2 ... 21155 21156 21157] [4662]
[    0     1     2 ... 21155 21156 21157] [4663]
[    0     1     2 ... 21155 21156 21157] [4664]
[    0     1     2 ... 21155 21156 21157] [4665]
[    0     1     2 ... 21155 21156 21157] [4666]
[    0     1     2 ... 21155 21156 21157] [4667]
[    0     1     2 ... 21155 21156 21157] [4668]
[    0     1     2 ... 21155 21156 21157] [4669]
[    0     1     2 ... 21155 21156 21157] [4670]
[    0     1     2 ... 21155 21156 21157] [4671]
[    0     1     2 ... 21155 21156 21157] [4672]
[    0     1     2 ... 21155 21156 21157] [4673]
[    0     1     2 ... 21155 21156 21157] [4674]
[    0     1     2 ... 21155 21156 21157] [4675]
[    0     1     2 ... 21155 21156 21157] [4676]
[    0     1     2 ... 21155 21156 21157] [4677]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [4904]
[    0     1     2 ... 21155 21156 21157] [4905]
[    0     1     2 ... 21155 21156 21157] [4906]
[    0     1     2 ... 21155 21156 21157] [4907]
[    0     1     2 ... 21155 21156 21157] [4908]
[    0     1     2 ... 21155 21156 21157] [4909]
[    0     1     2 ... 21155 21156 21157] [4910]
[    0     1     2 ... 21155 21156 21157] [4911]
[    0     1     2 ... 21155 21156 21157] [4912]
[    0     1     2 ... 21155 21156 21157] [4913]
[    0     1     2 ... 21155 21156 21157] [4914]
[    0     1     2 ... 21155 21156 21157] [4915]
[    0     1     2 ... 21155 21156 21157] [4916]
[    0     1     2 ... 21155 21156 21157] [4917]
[    0     1     2 ... 21155 21156 21157] [4918]
[    0     1     2 ... 21155 21156 21157] [4919]
[    0     1     2 ... 21155 21156 21157] [4920]
[    0     1     2 ... 21155 21156 21157] [4921]
[    0     1     2 ... 21155 21156 21157] [4922]
[    0     1     2 ... 21155 21156 21157] [4923]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [5167]
[    0     1     2 ... 21155 21156 21157] [5168]
[    0     1     2 ... 21155 21156 21157] [5169]
[    0     1     2 ... 21155 21156 21157] [5170]
[    0     1     2 ... 21155 21156 21157] [5171]
[    0     1     2 ... 21155 21156 21157] [5172]
[    0     1     2 ... 21155 21156 21157] [5173]
[    0     1     2 ... 21155 21156 21157] [5174]
[    0     1     2 ... 21155 21156 21157] [5175]
[    0     1     2 ... 21155 21156 21157] [5176]
[    0     1     2 ... 21155 21156 21157] [5177]
[    0     1     2 ... 21155 21156 21157] [5178]
[    0     1     2 ... 21155 21156 21157] [5179]
[    0     1     2 ... 21155 21156 21157] [5180]
[    0     1     2 ... 21155 21156 21157] [5181]
[    0     1     2 ... 21155 21156 21157] [5182]
[    0     1     2 ... 21155 21156 21157] [5183]
[    0     1     2 ... 21155 21156 21157] [5184]
[    0     1     2 ... 21155 21156 21157] [5185]
[    0     1     2 ... 21155 21156 21157] [5186]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [5424]
[    0     1     2 ... 21155 21156 21157] [5425]
[    0     1     2 ... 21155 21156 21157] [5426]
[    0     1     2 ... 21155 21156 21157] [5427]
[    0     1     2 ... 21155 21156 21157] [5428]
[    0     1     2 ... 21155 21156 21157] [5429]
[    0     1     2 ... 21155 21156 21157] [5430]
[    0     1     2 ... 21155 21156 21157] [5431]
[    0     1     2 ... 21155 21156 21157] [5432]
[    0     1     2 ... 21155 21156 21157] [5433]
[    0     1     2 ... 21155 21156 21157] [5434]
[    0     1     2 ... 21155 21156 21157] [5435]
[    0     1     2 ... 21155 21156 21157] [5436]
[    0     1     2 ... 21155 21156 21157] [5437]
[    0     1     2 ... 21155 21156 21157] [5438]
[    0     1     2 ... 21155 21156 21157] [5439]
[    0     1     2 ... 21155 21156 21157] [5440]
[    0     1     2 ... 21155 21156 21157] [5441]
[    0     1     2 ... 21155 21156 21157] [5442]
[    0     1     2 ... 21155 21156 21157] [5443]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [5684]
[    0     1     2 ... 21155 21156 21157] [5685]
[    0     1     2 ... 21155 21156 21157] [5686]
[    0     1     2 ... 21155 21156 21157] [5687]
[    0     1     2 ... 21155 21156 21157] [5688]
[    0     1     2 ... 21155 21156 21157] [5689]
[    0     1     2 ... 21155 21156 21157] [5690]
[    0     1     2 ... 21155 21156 21157] [5691]
[    0     1     2 ... 21155 21156 21157] [5692]
[    0     1     2 ... 21155 21156 21157] [5693]
[    0     1     2 ... 21155 21156 21157] [5694]
[    0     1     2 ... 21155 21156 21157] [5695]
[    0     1     2 ... 21155 21156 21157] [5696]
[    0     1     2 ... 21155 21156 21157] [5697]
[    0     1     2 ... 21155 21156 21157] [5698]
[    0     1     2 ... 21155 21156 21157] [5699]
[    0     1     2 ... 21155 21156 21157] [5700]
[    0     1     2 ... 21155 21156 21157] [5701]
[    0     1     2 ... 21155 21156 21157] [5702]
[    0     1     2 ... 21155 21156 21157] [5703]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [5958]
[    0     1     2 ... 21155 21156 21157] [5959]
[    0     1     2 ... 21155 21156 21157] [5960]
[    0     1     2 ... 21155 21156 21157] [5961]
[    0     1     2 ... 21155 21156 21157] [5962]
[    0     1     2 ... 21155 21156 21157] [5963]
[    0     1     2 ... 21155 21156 21157] [5964]
[    0     1     2 ... 21155 21156 21157] [5965]
[    0     1     2 ... 21155 21156 21157] [5966]
[    0     1     2 ... 21155 21156 21157] [5967]
[    0     1     2 ... 21155 21156 21157] [5968]
[    0     1     2 ... 21155 21156 21157] [5969]
[    0     1     2 ... 21155 21156 21157] [5970]
[    0     1     2 ... 21155 21156 21157] [5971]
[    0     1     2 ... 21155 21156 21157] [5972]
[    0     1     2 ... 21155 21156 21157] [5973]
[    0     1     2 ... 21155 21156 21157] [5974]
[    0     1     2 ... 21155 21156 21157] [5975]
[    0     1     2 ... 21155 21156 21157] [5976]
[    0     1     2 ... 21155 21156 21157] [5977]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [6229]
[    0     1     2 ... 21155 21156 21157] [6230]
[    0     1     2 ... 21155 21156 21157] [6231]
[    0     1     2 ... 21155 21156 21157] [6232]
[    0     1     2 ... 21155 21156 21157] [6233]
[    0     1     2 ... 21155 21156 21157] [6234]
[    0     1     2 ... 21155 21156 21157] [6235]
[    0     1     2 ... 21155 21156 21157] [6236]
[    0     1     2 ... 21155 21156 21157] [6237]
[    0     1     2 ... 21155 21156 21157] [6238]
[    0     1     2 ... 21155 21156 21157] [6239]
[    0     1     2 ... 21155 21156 21157] [6240]
[    0     1     2 ... 21155 21156 21157] [6241]
[    0     1     2 ... 21155 21156 21157] [6242]
[    0     1     2 ... 21155 21156 21157] [6243]
[    0     1     2 ... 21155 21156 21157] [6244]
[    0     1     2 ... 21155 21156 21157] [6245]
[    0     1     2 ... 21155 21156 21157] [6246]
[    0     1     2 ... 21155 21156 21157] [6247]
[    0     1     2 ... 21155 21156 21157] [6248]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [6502]
[    0     1     2 ... 21155 21156 21157] [6503]
[    0     1     2 ... 21155 21156 21157] [6504]
[    0     1     2 ... 21155 21156 21157] [6505]
[    0     1     2 ... 21155 21156 21157] [6506]
[    0     1     2 ... 21155 21156 21157] [6507]
[    0     1     2 ... 21155 21156 21157] [6508]
[    0     1     2 ... 21155 21156 21157] [6509]
[    0     1     2 ... 21155 21156 21157] [6510]
[    0     1     2 ... 21155 21156 21157] [6511]
[    0     1     2 ... 21155 21156 21157] [6512]
[    0     1     2 ... 21155 21156 21157] [6513]
[    0     1     2 ... 21155 21156 21157] [6514]
[    0     1     2 ... 21155 21156 21157] [6515]
[    0     1     2 ... 21155 21156 21157] [6516]
[    0     1     2 ... 21155 21156 21157] [6517]
[    0     1     2 ... 21155 21156 21157] [6518]
[    0     1     2 ... 21155 21156 21157] [6519]
[    0     1     2 ... 21155 21156 21157] [6520]
[    0     1     2 ... 21155 21156 21157] [6521]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [6773]
[    0     1     2 ... 21155 21156 21157] [6774]
[    0     1     2 ... 21155 21156 21157] [6775]
[    0     1     2 ... 21155 21156 21157] [6776]
[    0     1     2 ... 21155 21156 21157] [6777]
[    0     1     2 ... 21155 21156 21157] [6778]
[    0     1     2 ... 21155 21156 21157] [6779]
[    0     1     2 ... 21155 21156 21157] [6780]
[    0     1     2 ... 21155 21156 21157] [6781]
[    0     1     2 ... 21155 21156 21157] [6782]
[    0     1     2 ... 21155 21156 21157] [6783]
[    0     1     2 ... 21155 21156 21157] [6784]
[    0     1     2 ... 21155 21156 21157] [6785]
[    0     1     2 ... 21155 21156 21157] [6786]
[    0     1     2 ... 21155 21156 21157] [6787]
[    0     1     2 ... 21155 21156 21157] [6788]
[    0     1     2 ... 21155 21156 21157] [6789]
[    0     1     2 ... 21155 21156 21157] [6790]
[    0     1     2 ... 21155 21156 21157] [6791]
[    0     1     2 ... 21155 21156 21157] [6792]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [7029]
[    0     1     2 ... 21155 21156 21157] [7030]
[    0     1     2 ... 21155 21156 21157] [7031]
[    0     1     2 ... 21155 21156 21157] [7032]
[    0     1     2 ... 21155 21156 21157] [7033]
[    0     1     2 ... 21155 21156 21157] [7034]
[    0     1     2 ... 21155 21156 21157] [7035]
[    0     1     2 ... 21155 21156 21157] [7036]
[    0     1     2 ... 21155 21156 21157] [7037]
[    0     1     2 ... 21155 21156 21157] [7038]
[    0     1     2 ... 21155 21156 21157] [7039]
[    0     1     2 ... 21155 21156 21157] [7040]
[    0     1     2 ... 21155 21156 21157] [7041]
[    0     1     2 ... 21155 21156 21157] [7042]
[    0     1     2 ... 21155 21156 21157] [7043]
[    0     1     2 ... 21155 21156 21157] [7044]
[    0     1     2 ... 21155 21156 21157] [7045]
[    0     1     2 ... 21155 21156 21157] [7046]
[    0     1     2 ... 21155 21156 21157] [7047]
[    0     1     2 ... 21155 21156 21157] [7048]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [7302]
[    0     1     2 ... 21155 21156 21157] [7303]
[    0     1     2 ... 21155 21156 21157] [7304]
[    0     1     2 ... 21155 21156 21157] [7305]
[    0     1     2 ... 21155 21156 21157] [7306]
[    0     1     2 ... 21155 21156 21157] [7307]
[    0     1     2 ... 21155 21156 21157] [7308]
[    0     1     2 ... 21155 21156 21157] [7309]
[    0     1     2 ... 21155 21156 21157] [7310]
[    0     1     2 ... 21155 21156 21157] [7311]
[    0     1     2 ... 21155 21156 21157] [7312]
[    0     1     2 ... 21155 21156 21157] [7313]
[    0     1     2 ... 21155 21156 21157] [7314]
[    0     1     2 ... 21155 21156 21157] [7315]
[    0     1     2 ... 21155 21156 21157] [7316]
[    0     1     2 ... 21155 21156 21157] [7317]
[    0     1     2 ... 21155 21156 21157] [7318]
[    0     1     2 ... 21155 21156 21157] [7319]
[    0     1     2 ... 21155 21156 21157] [7320]
[    0     1     2 ... 21155 21156 21157] [7321]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [7572]
[    0     1     2 ... 21155 21156 21157] [7573]
[    0     1     2 ... 21155 21156 21157] [7574]
[    0     1     2 ... 21155 21156 21157] [7575]
[    0     1     2 ... 21155 21156 21157] [7576]
[    0     1     2 ... 21155 21156 21157] [7577]
[    0     1     2 ... 21155 21156 21157] [7578]
[    0     1     2 ... 21155 21156 21157] [7579]
[    0     1     2 ... 21155 21156 21157] [7580]
[    0     1     2 ... 21155 21156 21157] [7581]
[    0     1     2 ... 21155 21156 21157] [7582]
[    0     1     2 ... 21155 21156 21157] [7583]
[    0     1     2 ... 21155 21156 21157] [7584]
[    0     1     2 ... 21155 21156 21157] [7585]
[    0     1     2 ... 21155 21156 21157] [7586]
[    0     1     2 ... 21155 21156 21157] [7587]
[    0     1     2 ... 21155 21156 21157] [7588]
[    0     1     2 ... 21155 21156 21157] [7589]
[    0     1     2 ... 21155 21156 21157] [7590]
[    0     1     2 ... 21155 21156 21157] [7591]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [7828]
[    0     1     2 ... 21155 21156 21157] [7829]
[    0     1     2 ... 21155 21156 21157] [7830]
[    0     1     2 ... 21155 21156 21157] [7831]
[    0     1     2 ... 21155 21156 21157] [7832]
[    0     1     2 ... 21155 21156 21157] [7833]
[    0     1     2 ... 21155 21156 21157] [7834]
[    0     1     2 ... 21155 21156 21157] [7835]
[    0     1     2 ... 21155 21156 21157] [7836]
[    0     1     2 ... 21155 21156 21157] [7837]
[    0     1     2 ... 21155 21156 21157] [7838]
[    0     1     2 ... 21155 21156 21157] [7839]
[    0     1     2 ... 21155 21156 21157] [7840]
[    0     1     2 ... 21155 21156 21157] [7841]
[    0     1     2 ... 21155 21156 21157] [7842]
[    0     1     2 ... 21155 21156 21157] [7843]
[    0     1     2 ... 21155 21156 21157] [7844]
[    0     1     2 ... 21155 21156 21157] [7845]
[    0     1     2 ... 21155 21156 21157] [7846]
[    0     1     2 ... 21155 21156 21157] [7847]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [8097]
[    0     1     2 ... 21155 21156 21157] [8098]
[    0     1     2 ... 21155 21156 21157] [8099]
[    0     1     2 ... 21155 21156 21157] [8100]
[    0     1     2 ... 21155 21156 21157] [8101]
[    0     1     2 ... 21155 21156 21157] [8102]
[    0     1     2 ... 21155 21156 21157] [8103]
[    0     1     2 ... 21155 21156 21157] [8104]
[    0     1     2 ... 21155 21156 21157] [8105]
[    0     1     2 ... 21155 21156 21157] [8106]
[    0     1     2 ... 21155 21156 21157] [8107]
[    0     1     2 ... 21155 21156 21157] [8108]
[    0     1     2 ... 21155 21156 21157] [8109]
[    0     1     2 ... 21155 21156 21157] [8110]
[    0     1     2 ... 21155 21156 21157] [8111]
[    0     1     2 ... 21155 21156 21157] [8112]
[    0     1     2 ... 21155 21156 21157] [8113]
[    0     1     2 ... 21155 21156 21157] [8114]
[    0     1     2 ... 21155 21156 21157] [8115]
[    0     1     2 ... 21155 21156 21157] [8116]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [8363]
[    0     1     2 ... 21155 21156 21157] [8364]
[    0     1     2 ... 21155 21156 21157] [8365]
[    0     1     2 ... 21155 21156 21157] [8366]
[    0     1     2 ... 21155 21156 21157] [8367]
[    0     1     2 ... 21155 21156 21157] [8368]
[    0     1     2 ... 21155 21156 21157] [8369]
[    0     1     2 ... 21155 21156 21157] [8370]
[    0     1     2 ... 21155 21156 21157] [8371]
[    0     1     2 ... 21155 21156 21157] [8372]
[    0     1     2 ... 21155 21156 21157] [8373]
[    0     1     2 ... 21155 21156 21157] [8374]
[    0     1     2 ... 21155 21156 21157] [8375]
[    0     1     2 ... 21155 21156 21157] [8376]
[    0     1     2 ... 21155 21156 21157] [8377]
[    0     1     2 ... 21155 21156 21157] [8378]
[    0     1     2 ... 21155 21156 21157] [8379]
[    0     1     2 ... 21155 21156 21157] [8380]
[    0     1     2 ... 21155 21156 21157] [8381]
[    0     1     2 ... 21155 21156 21157] [8382]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [8631]
[    0     1     2 ... 21155 21156 21157] [8632]
[    0     1     2 ... 21155 21156 21157] [8633]
[    0     1     2 ... 21155 21156 21157] [8634]
[    0     1     2 ... 21155 21156 21157] [8635]
[    0     1     2 ... 21155 21156 21157] [8636]
[    0     1     2 ... 21155 21156 21157] [8637]
[    0     1     2 ... 21155 21156 21157] [8638]
[    0     1     2 ... 21155 21156 21157] [8639]
[    0     1     2 ... 21155 21156 21157] [8640]
[    0     1     2 ... 21155 21156 21157] [8641]
[    0     1     2 ... 21155 21156 21157] [8642]
[    0     1     2 ... 21155 21156 21157] [8643]
[    0     1     2 ... 21155 21156 21157] [8644]
[    0     1     2 ... 21155 21156 21157] [8645]
[    0     1     2 ... 21155 21156 21157] [8646]
[    0     1     2 ... 21155 21156 21157] [8647]
[    0     1     2 ... 21155 21156 21157] [8648]
[    0     1     2 ... 21155 21156 21157] [8649]
[    0     1     2 ... 21155 21156 21157] [8650]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [8905]
[    0     1     2 ... 21155 21156 21157] [8906]
[    0     1     2 ... 21155 21156 21157] [8907]
[    0     1     2 ... 21155 21156 21157] [8908]
[    0     1     2 ... 21155 21156 21157] [8909]
[    0     1     2 ... 21155 21156 21157] [8910]
[    0     1     2 ... 21155 21156 21157] [8911]
[    0     1     2 ... 21155 21156 21157] [8912]
[    0     1     2 ... 21155 21156 21157] [8913]
[    0     1     2 ... 21155 21156 21157] [8914]
[    0     1     2 ... 21155 21156 21157] [8915]
[    0     1     2 ... 21155 21156 21157] [8916]
[    0     1     2 ... 21155 21156 21157] [8917]
[    0     1     2 ... 21155 21156 21157] [8918]
[    0     1     2 ... 21155 21156 21157] [8919]
[    0     1     2 ... 21155 21156 21157] [8920]
[    0     1     2 ... 21155 21156 21157] [8921]
[    0     1     2 ... 21155 21156 21157] [8922]
[    0     1     2 ... 21155 21156 21157] [8923]
[    0     1     2 ... 21155 21156 21157] [8924]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [9170]
[    0     1     2 ... 21155 21156 21157] [9171]
[    0     1     2 ... 21155 21156 21157] [9172]
[    0     1     2 ... 21155 21156 21157] [9173]
[    0     1     2 ... 21155 21156 21157] [9174]
[    0     1     2 ... 21155 21156 21157] [9175]
[    0     1     2 ... 21155 21156 21157] [9176]
[    0     1     2 ... 21155 21156 21157] [9177]
[    0     1     2 ... 21155 21156 21157] [9178]
[    0     1     2 ... 21155 21156 21157] [9179]
[    0     1     2 ... 21155 21156 21157] [9180]
[    0     1     2 ... 21155 21156 21157] [9181]
[    0     1     2 ... 21155 21156 21157] [9182]
[    0     1     2 ... 21155 21156 21157] [9183]
[    0     1     2 ... 21155 21156 21157] [9184]
[    0     1     2 ... 21155 21156 21157] [9185]
[    0     1     2 ... 21155 21156 21157] [9186]
[    0     1     2 ... 21155 21156 21157] [9187]
[    0     1     2 ... 21155 21156 21157] [9188]
[    0     1     2 ... 21155 21156 21157] [9189]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [9433]
[    0     1     2 ... 21155 21156 21157] [9434]
[    0     1     2 ... 21155 21156 21157] [9435]
[    0     1     2 ... 21155 21156 21157] [9436]
[    0     1     2 ... 21155 21156 21157] [9437]
[    0     1     2 ... 21155 21156 21157] [9438]
[    0     1     2 ... 21155 21156 21157] [9439]
[    0     1     2 ... 21155 21156 21157] [9440]
[    0     1     2 ... 21155 21156 21157] [9441]
[    0     1     2 ... 21155 21156 21157] [9442]
[    0     1     2 ... 21155 21156 21157] [9443]
[    0     1     2 ... 21155 21156 21157] [9444]
[    0     1     2 ... 21155 21156 21157] [9445]
[    0     1     2 ... 21155 21156 21157] [9446]
[    0     1     2 ... 21155 21156 21157] [9447]
[    0     1     2 ... 21155 21156 21157] [9448]
[    0     1     2 ... 21155 21156 21157] [9449]
[    0     1     2 ... 21155 21156 21157] [9450]
[    0     1     2 ... 21155 21156 21157] [9451]
[    0     1     2 ... 21155 21156 21157] [9452]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [9684]
[    0     1     2 ... 21155 21156 21157] [9685]
[    0     1     2 ... 21155 21156 21157] [9686]
[    0     1     2 ... 21155 21156 21157] [9687]
[    0     1     2 ... 21155 21156 21157] [9688]
[    0     1     2 ... 21155 21156 21157] [9689]
[    0     1     2 ... 21155 21156 21157] [9690]
[    0     1     2 ... 21155 21156 21157] [9691]
[    0     1     2 ... 21155 21156 21157] [9692]
[    0     1     2 ... 21155 21156 21157] [9693]
[    0     1     2 ... 21155 21156 21157] [9694]
[    0     1     2 ... 21155 21156 21157] [9695]
[    0     1     2 ... 21155 21156 21157] [9696]
[    0     1     2 ... 21155 21156 21157] [9697]
[    0     1     2 ... 21155 21156 21157] [9698]
[    0     1     2 ... 21155 21156 21157] [9699]
[    0     1     2 ... 21155 21156 21157] [9700]
[    0     1     2 ... 21155 21156 21157] [9701]
[    0     1     2 ... 21155 21156 21157] [9702]
[    0     1     2 ... 21155 21156 21157] [9703]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [9895]
[    0     1     2 ... 21155 21156 21157] [9896]
[    0     1     2 ... 21155 21156 21157] [9897]
[    0     1     2 ... 21155 21156 21157] [9898]
[    0     1     2 ... 21155 21156 21157] [9899]
[    0     1     2 ... 21155 21156 21157] [9900]
[    0     1     2 ... 21155 21156 21157] [9901]
[    0     1     2 ... 21155 21156 21157] [9902]
[    0     1     2 ... 21155 21156 21157] [9903]
[    0     1     2 ... 21155 21156 21157] [9904]
[    0     1     2 ... 21155 21156 21157] [9905]
[    0     1     2 ... 21155 21156 21157] [9906]
[    0     1     2 ... 21155 21156 21157] [9907]
[    0     1     2 ... 21155 21156 21157] [9908]
[    0     1     2 ... 21155 21156 21157] [9909]
[    0     1     2 ... 21155 21156 21157] [9910]
[    0     1     2 ... 21155 21156 21157] [9911]
[    0     1     2 ... 21155 21156 21157] [9912]
[    0     1     2 ... 21155 21156 21157] [9913]
[    0     1     2 ... 21155 21156 21157] [9914]
[    0     1     2 .

[    0     1     2 ... 21155 21156 21157] [10076]
[    0     1     2 ... 21155 21156 21157] [10077]
[    0     1     2 ... 21155 21156 21157] [10078]
[    0     1     2 ... 21155 21156 21157] [10079]
[    0     1     2 ... 21155 21156 21157] [10080]
[    0     1     2 ... 21155 21156 21157] [10081]
[    0     1     2 ... 21155 21156 21157] [10082]
[    0     1     2 ... 21155 21156 21157] [10083]
[    0     1     2 ... 21155 21156 21157] [10084]
[    0     1     2 ... 21155 21156 21157] [10085]
[    0     1     2 ... 21155 21156 21157] [10086]
[    0     1     2 ... 21155 21156 21157] [10087]
[    0     1     2 ... 21155 21156 21157] [10088]
[    0     1     2 ... 21155 21156 21157] [10089]
[    0     1     2 ... 21155 21156 21157] [10090]
[    0     1     2 ... 21155 21156 21157] [10091]
[    0     1     2 ... 21155 21156 21157] [10092]
[    0     1     2 ... 21155 21156 21157] [10093]
[    0     1     2 ... 21155 21156 21157] [10094]
[    0     1     2 ... 21155 21156 21157] [10095]


[    0     1     2 ... 21155 21156 21157] [10257]
[    0     1     2 ... 21155 21156 21157] [10258]
[    0     1     2 ... 21155 21156 21157] [10259]
[    0     1     2 ... 21155 21156 21157] [10260]
[    0     1     2 ... 21155 21156 21157] [10261]
[    0     1     2 ... 21155 21156 21157] [10262]
[    0     1     2 ... 21155 21156 21157] [10263]
[    0     1     2 ... 21155 21156 21157] [10264]
[    0     1     2 ... 21155 21156 21157] [10265]
[    0     1     2 ... 21155 21156 21157] [10266]
[    0     1     2 ... 21155 21156 21157] [10267]
[    0     1     2 ... 21155 21156 21157] [10268]
[    0     1     2 ... 21155 21156 21157] [10269]
[    0     1     2 ... 21155 21156 21157] [10270]
[    0     1     2 ... 21155 21156 21157] [10271]
[    0     1     2 ... 21155 21156 21157] [10272]
[    0     1     2 ... 21155 21156 21157] [10273]
[    0     1     2 ... 21155 21156 21157] [10274]
[    0     1     2 ... 21155 21156 21157] [10275]
[    0     1     2 ... 21155 21156 21157] [10276]


[    0     1     2 ... 21155 21156 21157] [10454]
[    0     1     2 ... 21155 21156 21157] [10455]
[    0     1     2 ... 21155 21156 21157] [10456]
[    0     1     2 ... 21155 21156 21157] [10457]
[    0     1     2 ... 21155 21156 21157] [10458]
[    0     1     2 ... 21155 21156 21157] [10459]
[    0     1     2 ... 21155 21156 21157] [10460]
[    0     1     2 ... 21155 21156 21157] [10461]
[    0     1     2 ... 21155 21156 21157] [10462]
[    0     1     2 ... 21155 21156 21157] [10463]
[    0     1     2 ... 21155 21156 21157] [10464]
[    0     1     2 ... 21155 21156 21157] [10465]
[    0     1     2 ... 21155 21156 21157] [10466]
[    0     1     2 ... 21155 21156 21157] [10467]
[    0     1     2 ... 21155 21156 21157] [10468]
[    0     1     2 ... 21155 21156 21157] [10469]
[    0     1     2 ... 21155 21156 21157] [10470]
[    0     1     2 ... 21155 21156 21157] [10471]
[    0     1     2 ... 21155 21156 21157] [10472]
[    0     1     2 ... 21155 21156 21157] [10473]


[    0     1     2 ... 21155 21156 21157] [10646]
[    0     1     2 ... 21155 21156 21157] [10647]
[    0     1     2 ... 21155 21156 21157] [10648]
[    0     1     2 ... 21155 21156 21157] [10649]
[    0     1     2 ... 21155 21156 21157] [10650]
[    0     1     2 ... 21155 21156 21157] [10651]
[    0     1     2 ... 21155 21156 21157] [10652]
[    0     1     2 ... 21155 21156 21157] [10653]
[    0     1     2 ... 21155 21156 21157] [10654]
[    0     1     2 ... 21155 21156 21157] [10655]
[    0     1     2 ... 21155 21156 21157] [10656]
[    0     1     2 ... 21155 21156 21157] [10657]
[    0     1     2 ... 21155 21156 21157] [10658]
[    0     1     2 ... 21155 21156 21157] [10659]
[    0     1     2 ... 21155 21156 21157] [10660]
[    0     1     2 ... 21155 21156 21157] [10661]
[    0     1     2 ... 21155 21156 21157] [10662]
[    0     1     2 ... 21155 21156 21157] [10663]
[    0     1     2 ... 21155 21156 21157] [10664]
[    0     1     2 ... 21155 21156 21157] [10665]


[    0     1     2 ... 21155 21156 21157] [10875]
[    0     1     2 ... 21155 21156 21157] [10876]
[    0     1     2 ... 21155 21156 21157] [10877]
[    0     1     2 ... 21155 21156 21157] [10878]
[    0     1     2 ... 21155 21156 21157] [10879]
[    0     1     2 ... 21155 21156 21157] [10880]
[    0     1     2 ... 21155 21156 21157] [10881]
[    0     1     2 ... 21155 21156 21157] [10882]
[    0     1     2 ... 21155 21156 21157] [10883]
[    0     1     2 ... 21155 21156 21157] [10884]
[    0     1     2 ... 21155 21156 21157] [10885]
[    0     1     2 ... 21155 21156 21157] [10886]
[    0     1     2 ... 21155 21156 21157] [10887]
[    0     1     2 ... 21155 21156 21157] [10888]
[    0     1     2 ... 21155 21156 21157] [10889]
[    0     1     2 ... 21155 21156 21157] [10890]
[    0     1     2 ... 21155 21156 21157] [10891]
[    0     1     2 ... 21155 21156 21157] [10892]
[    0     1     2 ... 21155 21156 21157] [10893]
[    0     1     2 ... 21155 21156 21157] [10894]


[    0     1     2 ... 21155 21156 21157] [11063]
[    0     1     2 ... 21155 21156 21157] [11064]
[    0     1     2 ... 21155 21156 21157] [11065]
[    0     1     2 ... 21155 21156 21157] [11066]
[    0     1     2 ... 21155 21156 21157] [11067]
[    0     1     2 ... 21155 21156 21157] [11068]
[    0     1     2 ... 21155 21156 21157] [11069]
[    0     1     2 ... 21155 21156 21157] [11070]
[    0     1     2 ... 21155 21156 21157] [11071]
[    0     1     2 ... 21155 21156 21157] [11072]
[    0     1     2 ... 21155 21156 21157] [11073]
[    0     1     2 ... 21155 21156 21157] [11074]
[    0     1     2 ... 21155 21156 21157] [11075]
[    0     1     2 ... 21155 21156 21157] [11076]
[    0     1     2 ... 21155 21156 21157] [11077]
[    0     1     2 ... 21155 21156 21157] [11078]
[    0     1     2 ... 21155 21156 21157] [11079]
[    0     1     2 ... 21155 21156 21157] [11080]
[    0     1     2 ... 21155 21156 21157] [11081]
[    0     1     2 ... 21155 21156 21157] [11082]


[    0     1     2 ... 21155 21156 21157] [11302]
[    0     1     2 ... 21155 21156 21157] [11303]
[    0     1     2 ... 21155 21156 21157] [11304]
[    0     1     2 ... 21155 21156 21157] [11305]
[    0     1     2 ... 21155 21156 21157] [11306]
[    0     1     2 ... 21155 21156 21157] [11307]
[    0     1     2 ... 21155 21156 21157] [11308]
[    0     1     2 ... 21155 21156 21157] [11309]
[    0     1     2 ... 21155 21156 21157] [11310]
[    0     1     2 ... 21155 21156 21157] [11311]
[    0     1     2 ... 21155 21156 21157] [11312]
[    0     1     2 ... 21155 21156 21157] [11313]
[    0     1     2 ... 21155 21156 21157] [11314]
[    0     1     2 ... 21155 21156 21157] [11315]
[    0     1     2 ... 21155 21156 21157] [11316]
[    0     1     2 ... 21155 21156 21157] [11317]
[    0     1     2 ... 21155 21156 21157] [11318]
[    0     1     2 ... 21155 21156 21157] [11319]
[    0     1     2 ... 21155 21156 21157] [11320]
[    0     1     2 ... 21155 21156 21157] [11321]


[    0     1     2 ... 21155 21156 21157] [11530]
[    0     1     2 ... 21155 21156 21157] [11531]
[    0     1     2 ... 21155 21156 21157] [11532]
[    0     1     2 ... 21155 21156 21157] [11533]
[    0     1     2 ... 21155 21156 21157] [11534]
[    0     1     2 ... 21155 21156 21157] [11535]
[    0     1     2 ... 21155 21156 21157] [11536]
[    0     1     2 ... 21155 21156 21157] [11537]
[    0     1     2 ... 21155 21156 21157] [11538]
[    0     1     2 ... 21155 21156 21157] [11539]
[    0     1     2 ... 21155 21156 21157] [11540]
[    0     1     2 ... 21155 21156 21157] [11541]
[    0     1     2 ... 21155 21156 21157] [11542]
[    0     1     2 ... 21155 21156 21157] [11543]
[    0     1     2 ... 21155 21156 21157] [11544]
[    0     1     2 ... 21155 21156 21157] [11545]
[    0     1     2 ... 21155 21156 21157] [11546]
[    0     1     2 ... 21155 21156 21157] [11547]
[    0     1     2 ... 21155 21156 21157] [11548]
[    0     1     2 ... 21155 21156 21157] [11549]


[    0     1     2 ... 21155 21156 21157] [11781]
[    0     1     2 ... 21155 21156 21157] [11782]
[    0     1     2 ... 21155 21156 21157] [11783]
[    0     1     2 ... 21155 21156 21157] [11784]
[    0     1     2 ... 21155 21156 21157] [11785]
[    0     1     2 ... 21155 21156 21157] [11786]
[    0     1     2 ... 21155 21156 21157] [11787]
[    0     1     2 ... 21155 21156 21157] [11788]
[    0     1     2 ... 21155 21156 21157] [11789]
[    0     1     2 ... 21155 21156 21157] [11790]
[    0     1     2 ... 21155 21156 21157] [11791]
[    0     1     2 ... 21155 21156 21157] [11792]
[    0     1     2 ... 21155 21156 21157] [11793]
[    0     1     2 ... 21155 21156 21157] [11794]
[    0     1     2 ... 21155 21156 21157] [11795]
[    0     1     2 ... 21155 21156 21157] [11796]
[    0     1     2 ... 21155 21156 21157] [11797]
[    0     1     2 ... 21155 21156 21157] [11798]
[    0     1     2 ... 21155 21156 21157] [11799]
[    0     1     2 ... 21155 21156 21157] [11800]


[    0     1     2 ... 21155 21156 21157] [12043]
[    0     1     2 ... 21155 21156 21157] [12044]
[    0     1     2 ... 21155 21156 21157] [12045]
[    0     1     2 ... 21155 21156 21157] [12046]
[    0     1     2 ... 21155 21156 21157] [12047]
[    0     1     2 ... 21155 21156 21157] [12048]
[    0     1     2 ... 21155 21156 21157] [12049]
[    0     1     2 ... 21155 21156 21157] [12050]
[    0     1     2 ... 21155 21156 21157] [12051]
[    0     1     2 ... 21155 21156 21157] [12052]
[    0     1     2 ... 21155 21156 21157] [12053]
[    0     1     2 ... 21155 21156 21157] [12054]
[    0     1     2 ... 21155 21156 21157] [12055]
[    0     1     2 ... 21155 21156 21157] [12056]
[    0     1     2 ... 21155 21156 21157] [12057]
[    0     1     2 ... 21155 21156 21157] [12058]
[    0     1     2 ... 21155 21156 21157] [12059]
[    0     1     2 ... 21155 21156 21157] [12060]
[    0     1     2 ... 21155 21156 21157] [12061]
[    0     1     2 ... 21155 21156 21157] [12062]


[    0     1     2 ... 21155 21156 21157] [12295]
[    0     1     2 ... 21155 21156 21157] [12296]
[    0     1     2 ... 21155 21156 21157] [12297]
[    0     1     2 ... 21155 21156 21157] [12298]
[    0     1     2 ... 21155 21156 21157] [12299]
[    0     1     2 ... 21155 21156 21157] [12300]
[    0     1     2 ... 21155 21156 21157] [12301]
[    0     1     2 ... 21155 21156 21157] [12302]
[    0     1     2 ... 21155 21156 21157] [12303]
[    0     1     2 ... 21155 21156 21157] [12304]
[    0     1     2 ... 21155 21156 21157] [12305]
[    0     1     2 ... 21155 21156 21157] [12306]
[    0     1     2 ... 21155 21156 21157] [12307]
[    0     1     2 ... 21155 21156 21157] [12308]
[    0     1     2 ... 21155 21156 21157] [12309]
[    0     1     2 ... 21155 21156 21157] [12310]
[    0     1     2 ... 21155 21156 21157] [12311]
[    0     1     2 ... 21155 21156 21157] [12312]
[    0     1     2 ... 21155 21156 21157] [12313]
[    0     1     2 ... 21155 21156 21157] [12314]


[    0     1     2 ... 21155 21156 21157] [12516]
[    0     1     2 ... 21155 21156 21157] [12517]
[    0     1     2 ... 21155 21156 21157] [12518]
[    0     1     2 ... 21155 21156 21157] [12519]
[    0     1     2 ... 21155 21156 21157] [12520]
[    0     1     2 ... 21155 21156 21157] [12521]
[    0     1     2 ... 21155 21156 21157] [12522]
[    0     1     2 ... 21155 21156 21157] [12523]
[    0     1     2 ... 21155 21156 21157] [12524]
[    0     1     2 ... 21155 21156 21157] [12525]
[    0     1     2 ... 21155 21156 21157] [12526]
[    0     1     2 ... 21155 21156 21157] [12527]
[    0     1     2 ... 21155 21156 21157] [12528]
[    0     1     2 ... 21155 21156 21157] [12529]
[    0     1     2 ... 21155 21156 21157] [12530]
[    0     1     2 ... 21155 21156 21157] [12531]
[    0     1     2 ... 21155 21156 21157] [12532]
[    0     1     2 ... 21155 21156 21157] [12533]
[    0     1     2 ... 21155 21156 21157] [12534]
[    0     1     2 ... 21155 21156 21157] [12535]


[    0     1     2 ... 21155 21156 21157] [12740]
[    0     1     2 ... 21155 21156 21157] [12741]
[    0     1     2 ... 21155 21156 21157] [12742]
[    0     1     2 ... 21155 21156 21157] [12743]
[    0     1     2 ... 21155 21156 21157] [12744]
[    0     1     2 ... 21155 21156 21157] [12745]
[    0     1     2 ... 21155 21156 21157] [12746]
[    0     1     2 ... 21155 21156 21157] [12747]
[    0     1     2 ... 21155 21156 21157] [12748]
[    0     1     2 ... 21155 21156 21157] [12749]
[    0     1     2 ... 21155 21156 21157] [12750]
[    0     1     2 ... 21155 21156 21157] [12751]
[    0     1     2 ... 21155 21156 21157] [12752]
[    0     1     2 ... 21155 21156 21157] [12753]
[    0     1     2 ... 21155 21156 21157] [12754]
[    0     1     2 ... 21155 21156 21157] [12755]
[    0     1     2 ... 21155 21156 21157] [12756]
[    0     1     2 ... 21155 21156 21157] [12757]
[    0     1     2 ... 21155 21156 21157] [12758]
[    0     1     2 ... 21155 21156 21157] [12759]


[    0     1     2 ... 21155 21156 21157] [12988]
[    0     1     2 ... 21155 21156 21157] [12989]
[    0     1     2 ... 21155 21156 21157] [12990]
[    0     1     2 ... 21155 21156 21157] [12991]
[    0     1     2 ... 21155 21156 21157] [12992]
[    0     1     2 ... 21155 21156 21157] [12993]
[    0     1     2 ... 21155 21156 21157] [12994]
[    0     1     2 ... 21155 21156 21157] [12995]
[    0     1     2 ... 21155 21156 21157] [12996]
[    0     1     2 ... 21155 21156 21157] [12997]
[    0     1     2 ... 21155 21156 21157] [12998]
[    0     1     2 ... 21155 21156 21157] [12999]
[    0     1     2 ... 21155 21156 21157] [13000]
[    0     1     2 ... 21155 21156 21157] [13001]
[    0     1     2 ... 21155 21156 21157] [13002]
[    0     1     2 ... 21155 21156 21157] [13003]
[    0     1     2 ... 21155 21156 21157] [13004]
[    0     1     2 ... 21155 21156 21157] [13005]
[    0     1     2 ... 21155 21156 21157] [13006]
[    0     1     2 ... 21155 21156 21157] [13007]


[    0     1     2 ... 21155 21156 21157] [13201]
[    0     1     2 ... 21155 21156 21157] [13202]
[    0     1     2 ... 21155 21156 21157] [13203]
[    0     1     2 ... 21155 21156 21157] [13204]
[    0     1     2 ... 21155 21156 21157] [13205]
[    0     1     2 ... 21155 21156 21157] [13206]
[    0     1     2 ... 21155 21156 21157] [13207]
[    0     1     2 ... 21155 21156 21157] [13208]
[    0     1     2 ... 21155 21156 21157] [13209]
[    0     1     2 ... 21155 21156 21157] [13210]
[    0     1     2 ... 21155 21156 21157] [13211]
[    0     1     2 ... 21155 21156 21157] [13212]
[    0     1     2 ... 21155 21156 21157] [13213]
[    0     1     2 ... 21155 21156 21157] [13214]
[    0     1     2 ... 21155 21156 21157] [13215]
[    0     1     2 ... 21155 21156 21157] [13216]
[    0     1     2 ... 21155 21156 21157] [13217]
[    0     1     2 ... 21155 21156 21157] [13218]
[    0     1     2 ... 21155 21156 21157] [13219]
[    0     1     2 ... 21155 21156 21157] [13220]


[    0     1     2 ... 21155 21156 21157] [13462]
[    0     1     2 ... 21155 21156 21157] [13463]
[    0     1     2 ... 21155 21156 21157] [13464]
[    0     1     2 ... 21155 21156 21157] [13465]
[    0     1     2 ... 21155 21156 21157] [13466]
[    0     1     2 ... 21155 21156 21157] [13467]
[    0     1     2 ... 21155 21156 21157] [13468]
[    0     1     2 ... 21155 21156 21157] [13469]
[    0     1     2 ... 21155 21156 21157] [13470]
[    0     1     2 ... 21155 21156 21157] [13471]
[    0     1     2 ... 21155 21156 21157] [13472]
[    0     1     2 ... 21155 21156 21157] [13473]
[    0     1     2 ... 21155 21156 21157] [13474]
[    0     1     2 ... 21155 21156 21157] [13475]
[    0     1     2 ... 21155 21156 21157] [13476]
[    0     1     2 ... 21155 21156 21157] [13477]
[    0     1     2 ... 21155 21156 21157] [13478]
[    0     1     2 ... 21155 21156 21157] [13479]
[    0     1     2 ... 21155 21156 21157] [13480]
[    0     1     2 ... 21155 21156 21157] [13481]


[    0     1     2 ... 21155 21156 21157] [13720]
[    0     1     2 ... 21155 21156 21157] [13721]
[    0     1     2 ... 21155 21156 21157] [13722]
[    0     1     2 ... 21155 21156 21157] [13723]
[    0     1     2 ... 21155 21156 21157] [13724]
[    0     1     2 ... 21155 21156 21157] [13725]
[    0     1     2 ... 21155 21156 21157] [13726]
[    0     1     2 ... 21155 21156 21157] [13727]
[    0     1     2 ... 21155 21156 21157] [13728]
[    0     1     2 ... 21155 21156 21157] [13729]
[    0     1     2 ... 21155 21156 21157] [13730]
[    0     1     2 ... 21155 21156 21157] [13731]
[    0     1     2 ... 21155 21156 21157] [13732]
[    0     1     2 ... 21155 21156 21157] [13733]
[    0     1     2 ... 21155 21156 21157] [13734]
[    0     1     2 ... 21155 21156 21157] [13735]
[    0     1     2 ... 21155 21156 21157] [13736]
[    0     1     2 ... 21155 21156 21157] [13737]
[    0     1     2 ... 21155 21156 21157] [13738]
[    0     1     2 ... 21155 21156 21157] [13739]


[    0     1     2 ... 21155 21156 21157] [13949]
[    0     1     2 ... 21155 21156 21157] [13950]
[    0     1     2 ... 21155 21156 21157] [13951]
[    0     1     2 ... 21155 21156 21157] [13952]
[    0     1     2 ... 21155 21156 21157] [13953]
[    0     1     2 ... 21155 21156 21157] [13954]
[    0     1     2 ... 21155 21156 21157] [13955]
[    0     1     2 ... 21155 21156 21157] [13956]
[    0     1     2 ... 21155 21156 21157] [13957]
[    0     1     2 ... 21155 21156 21157] [13958]
[    0     1     2 ... 21155 21156 21157] [13959]
[    0     1     2 ... 21155 21156 21157] [13960]
[    0     1     2 ... 21155 21156 21157] [13961]
[    0     1     2 ... 21155 21156 21157] [13962]
[    0     1     2 ... 21155 21156 21157] [13963]
[    0     1     2 ... 21155 21156 21157] [13964]
[    0     1     2 ... 21155 21156 21157] [13965]
[    0     1     2 ... 21155 21156 21157] [13966]
[    0     1     2 ... 21155 21156 21157] [13967]
[    0     1     2 ... 21155 21156 21157] [13968]


[    0     1     2 ... 21155 21156 21157] [14133]
[    0     1     2 ... 21155 21156 21157] [14134]
[    0     1     2 ... 21155 21156 21157] [14135]
[    0     1     2 ... 21155 21156 21157] [14136]
[    0     1     2 ... 21155 21156 21157] [14137]
[    0     1     2 ... 21155 21156 21157] [14138]
[    0     1     2 ... 21155 21156 21157] [14139]
[    0     1     2 ... 21155 21156 21157] [14140]
[    0     1     2 ... 21155 21156 21157] [14141]
[    0     1     2 ... 21155 21156 21157] [14142]
[    0     1     2 ... 21155 21156 21157] [14143]
[    0     1     2 ... 21155 21156 21157] [14144]
[    0     1     2 ... 21155 21156 21157] [14145]
[    0     1     2 ... 21155 21156 21157] [14146]
[    0     1     2 ... 21155 21156 21157] [14147]
[    0     1     2 ... 21155 21156 21157] [14148]
[    0     1     2 ... 21155 21156 21157] [14149]
[    0     1     2 ... 21155 21156 21157] [14150]
[    0     1     2 ... 21155 21156 21157] [14151]
[    0     1     2 ... 21155 21156 21157] [14152]


[    0     1     2 ... 21155 21156 21157] [14350]
[    0     1     2 ... 21155 21156 21157] [14351]
[    0     1     2 ... 21155 21156 21157] [14352]
[    0     1     2 ... 21155 21156 21157] [14353]
[    0     1     2 ... 21155 21156 21157] [14354]
[    0     1     2 ... 21155 21156 21157] [14355]
[    0     1     2 ... 21155 21156 21157] [14356]
[    0     1     2 ... 21155 21156 21157] [14357]
[    0     1     2 ... 21155 21156 21157] [14358]
[    0     1     2 ... 21155 21156 21157] [14359]
[    0     1     2 ... 21155 21156 21157] [14360]
[    0     1     2 ... 21155 21156 21157] [14361]
[    0     1     2 ... 21155 21156 21157] [14362]
[    0     1     2 ... 21155 21156 21157] [14363]
[    0     1     2 ... 21155 21156 21157] [14364]
[    0     1     2 ... 21155 21156 21157] [14365]
[    0     1     2 ... 21155 21156 21157] [14366]
[    0     1     2 ... 21155 21156 21157] [14367]
[    0     1     2 ... 21155 21156 21157] [14368]
[    0     1     2 ... 21155 21156 21157] [14369]


[    0     1     2 ... 21155 21156 21157] [14617]
[    0     1     2 ... 21155 21156 21157] [14618]
[    0     1     2 ... 21155 21156 21157] [14619]
[    0     1     2 ... 21155 21156 21157] [14620]
[    0     1     2 ... 21155 21156 21157] [14621]
[    0     1     2 ... 21155 21156 21157] [14622]
[    0     1     2 ... 21155 21156 21157] [14623]
[    0     1     2 ... 21155 21156 21157] [14624]
[    0     1     2 ... 21155 21156 21157] [14625]
[    0     1     2 ... 21155 21156 21157] [14626]
[    0     1     2 ... 21155 21156 21157] [14627]
[    0     1     2 ... 21155 21156 21157] [14628]
[    0     1     2 ... 21155 21156 21157] [14629]
[    0     1     2 ... 21155 21156 21157] [14630]
[    0     1     2 ... 21155 21156 21157] [14631]
[    0     1     2 ... 21155 21156 21157] [14632]
[    0     1     2 ... 21155 21156 21157] [14633]
[    0     1     2 ... 21155 21156 21157] [14634]
[    0     1     2 ... 21155 21156 21157] [14635]
[    0     1     2 ... 21155 21156 21157] [14636]


[    0     1     2 ... 21155 21156 21157] [14815]
[    0     1     2 ... 21155 21156 21157] [14816]
[    0     1     2 ... 21155 21156 21157] [14817]
[    0     1     2 ... 21155 21156 21157] [14818]
[    0     1     2 ... 21155 21156 21157] [14819]
[    0     1     2 ... 21155 21156 21157] [14820]
[    0     1     2 ... 21155 21156 21157] [14821]
[    0     1     2 ... 21155 21156 21157] [14822]
[    0     1     2 ... 21155 21156 21157] [14823]
[    0     1     2 ... 21155 21156 21157] [14824]
[    0     1     2 ... 21155 21156 21157] [14825]
[    0     1     2 ... 21155 21156 21157] [14826]
[    0     1     2 ... 21155 21156 21157] [14827]
[    0     1     2 ... 21155 21156 21157] [14828]
[    0     1     2 ... 21155 21156 21157] [14829]
[    0     1     2 ... 21155 21156 21157] [14830]
[    0     1     2 ... 21155 21156 21157] [14831]
[    0     1     2 ... 21155 21156 21157] [14832]
[    0     1     2 ... 21155 21156 21157] [14833]
[    0     1     2 ... 21155 21156 21157] [14834]


[    0     1     2 ... 21155 21156 21157] [15037]
[    0     1     2 ... 21155 21156 21157] [15038]
[    0     1     2 ... 21155 21156 21157] [15039]
[    0     1     2 ... 21155 21156 21157] [15040]
[    0     1     2 ... 21155 21156 21157] [15041]
[    0     1     2 ... 21155 21156 21157] [15042]
[    0     1     2 ... 21155 21156 21157] [15043]
[    0     1     2 ... 21155 21156 21157] [15044]
[    0     1     2 ... 21155 21156 21157] [15045]
[    0     1     2 ... 21155 21156 21157] [15046]
[    0     1     2 ... 21155 21156 21157] [15047]
[    0     1     2 ... 21155 21156 21157] [15048]
[    0     1     2 ... 21155 21156 21157] [15049]
[    0     1     2 ... 21155 21156 21157] [15050]
[    0     1     2 ... 21155 21156 21157] [15051]
[    0     1     2 ... 21155 21156 21157] [15052]
[    0     1     2 ... 21155 21156 21157] [15053]
[    0     1     2 ... 21155 21156 21157] [15054]
[    0     1     2 ... 21155 21156 21157] [15055]
[    0     1     2 ... 21155 21156 21157] [15056]


[    0     1     2 ... 21155 21156 21157] [15272]
[    0     1     2 ... 21155 21156 21157] [15273]
[    0     1     2 ... 21155 21156 21157] [15274]
[    0     1     2 ... 21155 21156 21157] [15275]
[    0     1     2 ... 21155 21156 21157] [15276]
[    0     1     2 ... 21155 21156 21157] [15277]
[    0     1     2 ... 21155 21156 21157] [15278]
[    0     1     2 ... 21155 21156 21157] [15279]
[    0     1     2 ... 21155 21156 21157] [15280]
[    0     1     2 ... 21155 21156 21157] [15281]
[    0     1     2 ... 21155 21156 21157] [15282]
[    0     1     2 ... 21155 21156 21157] [15283]
[    0     1     2 ... 21155 21156 21157] [15284]
[    0     1     2 ... 21155 21156 21157] [15285]
[    0     1     2 ... 21155 21156 21157] [15286]
[    0     1     2 ... 21155 21156 21157] [15287]
[    0     1     2 ... 21155 21156 21157] [15288]
[    0     1     2 ... 21155 21156 21157] [15289]
[    0     1     2 ... 21155 21156 21157] [15290]
[    0     1     2 ... 21155 21156 21157] [15291]


[    0     1     2 ... 21155 21156 21157] [15485]
[    0     1     2 ... 21155 21156 21157] [15486]
[    0     1     2 ... 21155 21156 21157] [15487]
[    0     1     2 ... 21155 21156 21157] [15488]
[    0     1     2 ... 21155 21156 21157] [15489]
[    0     1     2 ... 21155 21156 21157] [15490]
[    0     1     2 ... 21155 21156 21157] [15491]
[    0     1     2 ... 21155 21156 21157] [15492]
[    0     1     2 ... 21155 21156 21157] [15493]
[    0     1     2 ... 21155 21156 21157] [15494]
[    0     1     2 ... 21155 21156 21157] [15495]
[    0     1     2 ... 21155 21156 21157] [15496]
[    0     1     2 ... 21155 21156 21157] [15497]
[    0     1     2 ... 21155 21156 21157] [15498]
[    0     1     2 ... 21155 21156 21157] [15499]
[    0     1     2 ... 21155 21156 21157] [15500]
[    0     1     2 ... 21155 21156 21157] [15501]
[    0     1     2 ... 21155 21156 21157] [15502]
[    0     1     2 ... 21155 21156 21157] [15503]
[    0     1     2 ... 21155 21156 21157] [15504]


[    0     1     2 ... 21155 21156 21157] [15712]
[    0     1     2 ... 21155 21156 21157] [15713]
[    0     1     2 ... 21155 21156 21157] [15714]
[    0     1     2 ... 21155 21156 21157] [15715]
[    0     1     2 ... 21155 21156 21157] [15716]
[    0     1     2 ... 21155 21156 21157] [15717]
[    0     1     2 ... 21155 21156 21157] [15718]
[    0     1     2 ... 21155 21156 21157] [15719]
[    0     1     2 ... 21155 21156 21157] [15720]
[    0     1     2 ... 21155 21156 21157] [15721]
[    0     1     2 ... 21155 21156 21157] [15722]
[    0     1     2 ... 21155 21156 21157] [15723]
[    0     1     2 ... 21155 21156 21157] [15724]
[    0     1     2 ... 21155 21156 21157] [15725]
[    0     1     2 ... 21155 21156 21157] [15726]
[    0     1     2 ... 21155 21156 21157] [15727]
[    0     1     2 ... 21155 21156 21157] [15728]
[    0     1     2 ... 21155 21156 21157] [15729]
[    0     1     2 ... 21155 21156 21157] [15730]
[    0     1     2 ... 21155 21156 21157] [15731]


[    0     1     2 ... 21155 21156 21157] [15968]
[    0     1     2 ... 21155 21156 21157] [15969]
[    0     1     2 ... 21155 21156 21157] [15970]
[    0     1     2 ... 21155 21156 21157] [15971]
[    0     1     2 ... 21155 21156 21157] [15972]
[    0     1     2 ... 21155 21156 21157] [15973]
[    0     1     2 ... 21155 21156 21157] [15974]
[    0     1     2 ... 21155 21156 21157] [15975]
[    0     1     2 ... 21155 21156 21157] [15976]
[    0     1     2 ... 21155 21156 21157] [15977]
[    0     1     2 ... 21155 21156 21157] [15978]
[    0     1     2 ... 21155 21156 21157] [15979]
[    0     1     2 ... 21155 21156 21157] [15980]
[    0     1     2 ... 21155 21156 21157] [15981]
[    0     1     2 ... 21155 21156 21157] [15982]
[    0     1     2 ... 21155 21156 21157] [15983]
[    0     1     2 ... 21155 21156 21157] [15984]
[    0     1     2 ... 21155 21156 21157] [15985]
[    0     1     2 ... 21155 21156 21157] [15986]
[    0     1     2 ... 21155 21156 21157] [15987]


[    0     1     2 ... 21155 21156 21157] [16211]
[    0     1     2 ... 21155 21156 21157] [16212]
[    0     1     2 ... 21155 21156 21157] [16213]
[    0     1     2 ... 21155 21156 21157] [16214]
[    0     1     2 ... 21155 21156 21157] [16215]
[    0     1     2 ... 21155 21156 21157] [16216]
[    0     1     2 ... 21155 21156 21157] [16217]
[    0     1     2 ... 21155 21156 21157] [16218]
[    0     1     2 ... 21155 21156 21157] [16219]
[    0     1     2 ... 21155 21156 21157] [16220]
[    0     1     2 ... 21155 21156 21157] [16221]
[    0     1     2 ... 21155 21156 21157] [16222]
[    0     1     2 ... 21155 21156 21157] [16223]
[    0     1     2 ... 21155 21156 21157] [16224]
[    0     1     2 ... 21155 21156 21157] [16225]
[    0     1     2 ... 21155 21156 21157] [16226]
[    0     1     2 ... 21155 21156 21157] [16227]
[    0     1     2 ... 21155 21156 21157] [16228]
[    0     1     2 ... 21155 21156 21157] [16229]
[    0     1     2 ... 21155 21156 21157] [16230]


[    0     1     2 ... 21155 21156 21157] [16470]
[    0     1     2 ... 21155 21156 21157] [16471]
[    0     1     2 ... 21155 21156 21157] [16472]
[    0     1     2 ... 21155 21156 21157] [16473]
[    0     1     2 ... 21155 21156 21157] [16474]
[    0     1     2 ... 21155 21156 21157] [16475]
[    0     1     2 ... 21155 21156 21157] [16476]
[    0     1     2 ... 21155 21156 21157] [16477]
[    0     1     2 ... 21155 21156 21157] [16478]
[    0     1     2 ... 21155 21156 21157] [16479]
[    0     1     2 ... 21155 21156 21157] [16480]
[    0     1     2 ... 21155 21156 21157] [16481]
[    0     1     2 ... 21155 21156 21157] [16482]
[    0     1     2 ... 21155 21156 21157] [16483]
[    0     1     2 ... 21155 21156 21157] [16484]
[    0     1     2 ... 21155 21156 21157] [16485]
[    0     1     2 ... 21155 21156 21157] [16486]
[    0     1     2 ... 21155 21156 21157] [16487]
[    0     1     2 ... 21155 21156 21157] [16488]
[    0     1     2 ... 21155 21156 21157] [16489]


[    0     1     2 ... 21155 21156 21157] [16735]
[    0     1     2 ... 21155 21156 21157] [16736]
[    0     1     2 ... 21155 21156 21157] [16737]
[    0     1     2 ... 21155 21156 21157] [16738]
[    0     1     2 ... 21155 21156 21157] [16739]
[    0     1     2 ... 21155 21156 21157] [16740]
[    0     1     2 ... 21155 21156 21157] [16741]
[    0     1     2 ... 21155 21156 21157] [16742]
[    0     1     2 ... 21155 21156 21157] [16743]
[    0     1     2 ... 21155 21156 21157] [16744]
[    0     1     2 ... 21155 21156 21157] [16745]
[    0     1     2 ... 21155 21156 21157] [16746]
[    0     1     2 ... 21155 21156 21157] [16747]
[    0     1     2 ... 21155 21156 21157] [16748]
[    0     1     2 ... 21155 21156 21157] [16749]
[    0     1     2 ... 21155 21156 21157] [16750]
[    0     1     2 ... 21155 21156 21157] [16751]
[    0     1     2 ... 21155 21156 21157] [16752]
[    0     1     2 ... 21155 21156 21157] [16753]
[    0     1     2 ... 21155 21156 21157] [16754]


[    0     1     2 ... 21155 21156 21157] [16984]
[    0     1     2 ... 21155 21156 21157] [16985]
[    0     1     2 ... 21155 21156 21157] [16986]
[    0     1     2 ... 21155 21156 21157] [16987]
[    0     1     2 ... 21155 21156 21157] [16988]
[    0     1     2 ... 21155 21156 21157] [16989]
[    0     1     2 ... 21155 21156 21157] [16990]
[    0     1     2 ... 21155 21156 21157] [16991]
[    0     1     2 ... 21155 21156 21157] [16992]
[    0     1     2 ... 21155 21156 21157] [16993]
[    0     1     2 ... 21155 21156 21157] [16994]
[    0     1     2 ... 21155 21156 21157] [16995]
[    0     1     2 ... 21155 21156 21157] [16996]
[    0     1     2 ... 21155 21156 21157] [16997]
[    0     1     2 ... 21155 21156 21157] [16998]
[    0     1     2 ... 21155 21156 21157] [16999]
[    0     1     2 ... 21155 21156 21157] [17000]
[    0     1     2 ... 21155 21156 21157] [17001]
[    0     1     2 ... 21155 21156 21157] [17002]
[    0     1     2 ... 21155 21156 21157] [17003]


[    0     1     2 ... 21155 21156 21157] [17209]
[    0     1     2 ... 21155 21156 21157] [17210]
[    0     1     2 ... 21155 21156 21157] [17211]
[    0     1     2 ... 21155 21156 21157] [17212]
[    0     1     2 ... 21155 21156 21157] [17213]
[    0     1     2 ... 21155 21156 21157] [17214]
[    0     1     2 ... 21155 21156 21157] [17215]
[    0     1     2 ... 21155 21156 21157] [17216]
[    0     1     2 ... 21155 21156 21157] [17217]
[    0     1     2 ... 21155 21156 21157] [17218]
[    0     1     2 ... 21155 21156 21157] [17219]
[    0     1     2 ... 21155 21156 21157] [17220]
[    0     1     2 ... 21155 21156 21157] [17221]
[    0     1     2 ... 21155 21156 21157] [17222]
[    0     1     2 ... 21155 21156 21157] [17223]
[    0     1     2 ... 21155 21156 21157] [17224]
[    0     1     2 ... 21155 21156 21157] [17225]
[    0     1     2 ... 21155 21156 21157] [17226]
[    0     1     2 ... 21155 21156 21157] [17227]
[    0     1     2 ... 21155 21156 21157] [17228]


[    0     1     2 ... 21155 21156 21157] [17412]
[    0     1     2 ... 21155 21156 21157] [17413]
[    0     1     2 ... 21155 21156 21157] [17414]
[    0     1     2 ... 21155 21156 21157] [17415]
[    0     1     2 ... 21155 21156 21157] [17416]
[    0     1     2 ... 21155 21156 21157] [17417]
[    0     1     2 ... 21155 21156 21157] [17418]
[    0     1     2 ... 21155 21156 21157] [17419]
[    0     1     2 ... 21155 21156 21157] [17420]
[    0     1     2 ... 21155 21156 21157] [17421]
[    0     1     2 ... 21155 21156 21157] [17422]
[    0     1     2 ... 21155 21156 21157] [17423]
[    0     1     2 ... 21155 21156 21157] [17424]
[    0     1     2 ... 21155 21156 21157] [17425]
[    0     1     2 ... 21155 21156 21157] [17426]
[    0     1     2 ... 21155 21156 21157] [17427]
[    0     1     2 ... 21155 21156 21157] [17428]
[    0     1     2 ... 21155 21156 21157] [17429]
[    0     1     2 ... 21155 21156 21157] [17430]
[    0     1     2 ... 21155 21156 21157] [17431]


[    0     1     2 ... 21155 21156 21157] [17628]
[    0     1     2 ... 21155 21156 21157] [17629]
[    0     1     2 ... 21155 21156 21157] [17630]
[    0     1     2 ... 21155 21156 21157] [17631]
[    0     1     2 ... 21155 21156 21157] [17632]
[    0     1     2 ... 21155 21156 21157] [17633]
[    0     1     2 ... 21155 21156 21157] [17634]
[    0     1     2 ... 21155 21156 21157] [17635]
[    0     1     2 ... 21155 21156 21157] [17636]
[    0     1     2 ... 21155 21156 21157] [17637]
[    0     1     2 ... 21155 21156 21157] [17638]
[    0     1     2 ... 21155 21156 21157] [17639]
[    0     1     2 ... 21155 21156 21157] [17640]
[    0     1     2 ... 21155 21156 21157] [17641]
[    0     1     2 ... 21155 21156 21157] [17642]
[    0     1     2 ... 21155 21156 21157] [17643]
[    0     1     2 ... 21155 21156 21157] [17644]
[    0     1     2 ... 21155 21156 21157] [17645]
[    0     1     2 ... 21155 21156 21157] [17646]
[    0     1     2 ... 21155 21156 21157] [17647]


[    0     1     2 ... 21155 21156 21157] [17862]
[    0     1     2 ... 21155 21156 21157] [17863]
[    0     1     2 ... 21155 21156 21157] [17864]
[    0     1     2 ... 21155 21156 21157] [17865]
[    0     1     2 ... 21155 21156 21157] [17866]
[    0     1     2 ... 21155 21156 21157] [17867]
[    0     1     2 ... 21155 21156 21157] [17868]
[    0     1     2 ... 21155 21156 21157] [17869]
[    0     1     2 ... 21155 21156 21157] [17870]
[    0     1     2 ... 21155 21156 21157] [17871]
[    0     1     2 ... 21155 21156 21157] [17872]
[    0     1     2 ... 21155 21156 21157] [17873]
[    0     1     2 ... 21155 21156 21157] [17874]
[    0     1     2 ... 21155 21156 21157] [17875]
[    0     1     2 ... 21155 21156 21157] [17876]
[    0     1     2 ... 21155 21156 21157] [17877]
[    0     1     2 ... 21155 21156 21157] [17878]
[    0     1     2 ... 21155 21156 21157] [17879]
[    0     1     2 ... 21155 21156 21157] [17880]
[    0     1     2 ... 21155 21156 21157] [17881]


[    0     1     2 ... 21155 21156 21157] [18034]
[    0     1     2 ... 21155 21156 21157] [18035]
[    0     1     2 ... 21155 21156 21157] [18036]
[    0     1     2 ... 21155 21156 21157] [18037]
[    0     1     2 ... 21155 21156 21157] [18038]
[    0     1     2 ... 21155 21156 21157] [18039]
[    0     1     2 ... 21155 21156 21157] [18040]
[    0     1     2 ... 21155 21156 21157] [18041]
[    0     1     2 ... 21155 21156 21157] [18042]
[    0     1     2 ... 21155 21156 21157] [18043]
[    0     1     2 ... 21155 21156 21157] [18044]
[    0     1     2 ... 21155 21156 21157] [18045]
[    0     1     2 ... 21155 21156 21157] [18046]
[    0     1     2 ... 21155 21156 21157] [18047]
[    0     1     2 ... 21155 21156 21157] [18048]
[    0     1     2 ... 21155 21156 21157] [18049]
[    0     1     2 ... 21155 21156 21157] [18050]
[    0     1     2 ... 21155 21156 21157] [18051]
[    0     1     2 ... 21155 21156 21157] [18052]
[    0     1     2 ... 21155 21156 21157] [18053]


[    0     1     2 ... 21155 21156 21157] [18251]
[    0     1     2 ... 21155 21156 21157] [18252]
[    0     1     2 ... 21155 21156 21157] [18253]
[    0     1     2 ... 21155 21156 21157] [18254]
[    0     1     2 ... 21155 21156 21157] [18255]
[    0     1     2 ... 21155 21156 21157] [18256]
[    0     1     2 ... 21155 21156 21157] [18257]
[    0     1     2 ... 21155 21156 21157] [18258]
[    0     1     2 ... 21155 21156 21157] [18259]
[    0     1     2 ... 21155 21156 21157] [18260]
[    0     1     2 ... 21155 21156 21157] [18261]
[    0     1     2 ... 21155 21156 21157] [18262]
[    0     1     2 ... 21155 21156 21157] [18263]
[    0     1     2 ... 21155 21156 21157] [18264]
[    0     1     2 ... 21155 21156 21157] [18265]
[    0     1     2 ... 21155 21156 21157] [18266]
[    0     1     2 ... 21155 21156 21157] [18267]
[    0     1     2 ... 21155 21156 21157] [18268]
[    0     1     2 ... 21155 21156 21157] [18269]
[    0     1     2 ... 21155 21156 21157] [18270]


[    0     1     2 ... 21155 21156 21157] [18462]
[    0     1     2 ... 21155 21156 21157] [18463]
[    0     1     2 ... 21155 21156 21157] [18464]
[    0     1     2 ... 21155 21156 21157] [18465]
[    0     1     2 ... 21155 21156 21157] [18466]
[    0     1     2 ... 21155 21156 21157] [18467]
[    0     1     2 ... 21155 21156 21157] [18468]
[    0     1     2 ... 21155 21156 21157] [18469]
[    0     1     2 ... 21155 21156 21157] [18470]
[    0     1     2 ... 21155 21156 21157] [18471]
[    0     1     2 ... 21155 21156 21157] [18472]
[    0     1     2 ... 21155 21156 21157] [18473]
[    0     1     2 ... 21155 21156 21157] [18474]
[    0     1     2 ... 21155 21156 21157] [18475]
[    0     1     2 ... 21155 21156 21157] [18476]
[    0     1     2 ... 21155 21156 21157] [18477]
[    0     1     2 ... 21155 21156 21157] [18478]
[    0     1     2 ... 21155 21156 21157] [18479]
[    0     1     2 ... 21155 21156 21157] [18480]
[    0     1     2 ... 21155 21156 21157] [18481]


[    0     1     2 ... 21155 21156 21157] [18680]
[    0     1     2 ... 21155 21156 21157] [18681]
[    0     1     2 ... 21155 21156 21157] [18682]
[    0     1     2 ... 21155 21156 21157] [18683]
[    0     1     2 ... 21155 21156 21157] [18684]
[    0     1     2 ... 21155 21156 21157] [18685]
[    0     1     2 ... 21155 21156 21157] [18686]
[    0     1     2 ... 21155 21156 21157] [18687]
[    0     1     2 ... 21155 21156 21157] [18688]
[    0     1     2 ... 21155 21156 21157] [18689]
[    0     1     2 ... 21155 21156 21157] [18690]
[    0     1     2 ... 21155 21156 21157] [18691]
[    0     1     2 ... 21155 21156 21157] [18692]
[    0     1     2 ... 21155 21156 21157] [18693]
[    0     1     2 ... 21155 21156 21157] [18694]
[    0     1     2 ... 21155 21156 21157] [18695]
[    0     1     2 ... 21155 21156 21157] [18696]
[    0     1     2 ... 21155 21156 21157] [18697]
[    0     1     2 ... 21155 21156 21157] [18698]
[    0     1     2 ... 21155 21156 21157] [18699]


[    0     1     2 ... 21155 21156 21157] [18864]
[    0     1     2 ... 21155 21156 21157] [18865]
[    0     1     2 ... 21155 21156 21157] [18866]
[    0     1     2 ... 21155 21156 21157] [18867]
[    0     1     2 ... 21155 21156 21157] [18868]
[    0     1     2 ... 21155 21156 21157] [18869]
[    0     1     2 ... 21155 21156 21157] [18870]
[    0     1     2 ... 21155 21156 21157] [18871]
[    0     1     2 ... 21155 21156 21157] [18872]
[    0     1     2 ... 21155 21156 21157] [18873]
[    0     1     2 ... 21155 21156 21157] [18874]
[    0     1     2 ... 21155 21156 21157] [18875]
[    0     1     2 ... 21155 21156 21157] [18876]
[    0     1     2 ... 21155 21156 21157] [18877]
[    0     1     2 ... 21155 21156 21157] [18878]
[    0     1     2 ... 21155 21156 21157] [18879]
[    0     1     2 ... 21155 21156 21157] [18880]
[    0     1     2 ... 21155 21156 21157] [18881]
[    0     1     2 ... 21155 21156 21157] [18882]
[    0     1     2 ... 21155 21156 21157] [18883]


[    0     1     2 ... 21155 21156 21157] [19084]
[    0     1     2 ... 21155 21156 21157] [19085]
[    0     1     2 ... 21155 21156 21157] [19086]
[    0     1     2 ... 21155 21156 21157] [19087]
[    0     1     2 ... 21155 21156 21157] [19088]
[    0     1     2 ... 21155 21156 21157] [19089]
[    0     1     2 ... 21155 21156 21157] [19090]
[    0     1     2 ... 21155 21156 21157] [19091]
[    0     1     2 ... 21155 21156 21157] [19092]
[    0     1     2 ... 21155 21156 21157] [19093]
[    0     1     2 ... 21155 21156 21157] [19094]
[    0     1     2 ... 21155 21156 21157] [19095]
[    0     1     2 ... 21155 21156 21157] [19096]
[    0     1     2 ... 21155 21156 21157] [19097]
[    0     1     2 ... 21155 21156 21157] [19098]
[    0     1     2 ... 21155 21156 21157] [19099]
[    0     1     2 ... 21155 21156 21157] [19100]
[    0     1     2 ... 21155 21156 21157] [19101]
[    0     1     2 ... 21155 21156 21157] [19102]
[    0     1     2 ... 21155 21156 21157] [19103]


[    0     1     2 ... 21155 21156 21157] [19290]
[    0     1     2 ... 21155 21156 21157] [19291]
[    0     1     2 ... 21155 21156 21157] [19292]
[    0     1     2 ... 21155 21156 21157] [19293]
[    0     1     2 ... 21155 21156 21157] [19294]
[    0     1     2 ... 21155 21156 21157] [19295]
[    0     1     2 ... 21155 21156 21157] [19296]
[    0     1     2 ... 21155 21156 21157] [19297]
[    0     1     2 ... 21155 21156 21157] [19298]
[    0     1     2 ... 21155 21156 21157] [19299]
[    0     1     2 ... 21155 21156 21157] [19300]
[    0     1     2 ... 21155 21156 21157] [19301]
[    0     1     2 ... 21155 21156 21157] [19302]
[    0     1     2 ... 21155 21156 21157] [19303]
[    0     1     2 ... 21155 21156 21157] [19304]
[    0     1     2 ... 21155 21156 21157] [19305]
[    0     1     2 ... 21155 21156 21157] [19306]
[    0     1     2 ... 21155 21156 21157] [19307]
[    0     1     2 ... 21155 21156 21157] [19308]
[    0     1     2 ... 21155 21156 21157] [19309]


[    0     1     2 ... 21155 21156 21157] [19514]
[    0     1     2 ... 21155 21156 21157] [19515]
[    0     1     2 ... 21155 21156 21157] [19516]
[    0     1     2 ... 21155 21156 21157] [19517]
[    0     1     2 ... 21155 21156 21157] [19518]
[    0     1     2 ... 21155 21156 21157] [19519]
[    0     1     2 ... 21155 21156 21157] [19520]
[    0     1     2 ... 21155 21156 21157] [19521]
[    0     1     2 ... 21155 21156 21157] [19522]
[    0     1     2 ... 21155 21156 21157] [19523]
[    0     1     2 ... 21155 21156 21157] [19524]
[    0     1     2 ... 21155 21156 21157] [19525]
[    0     1     2 ... 21155 21156 21157] [19526]
[    0     1     2 ... 21155 21156 21157] [19527]
[    0     1     2 ... 21155 21156 21157] [19528]
[    0     1     2 ... 21155 21156 21157] [19529]
[    0     1     2 ... 21155 21156 21157] [19530]
[    0     1     2 ... 21155 21156 21157] [19531]
[    0     1     2 ... 21155 21156 21157] [19532]
[    0     1     2 ... 21155 21156 21157] [19533]


[    0     1     2 ... 21155 21156 21157] [19712]
[    0     1     2 ... 21155 21156 21157] [19713]
[    0     1     2 ... 21155 21156 21157] [19714]
[    0     1     2 ... 21155 21156 21157] [19715]
[    0     1     2 ... 21155 21156 21157] [19716]
[    0     1     2 ... 21155 21156 21157] [19717]
[    0     1     2 ... 21155 21156 21157] [19718]
[    0     1     2 ... 21155 21156 21157] [19719]
[    0     1     2 ... 21155 21156 21157] [19720]
[    0     1     2 ... 21155 21156 21157] [19721]
[    0     1     2 ... 21155 21156 21157] [19722]
[    0     1     2 ... 21155 21156 21157] [19723]
[    0     1     2 ... 21155 21156 21157] [19724]
[    0     1     2 ... 21155 21156 21157] [19725]
[    0     1     2 ... 21155 21156 21157] [19726]
[    0     1     2 ... 21155 21156 21157] [19727]
[    0     1     2 ... 21155 21156 21157] [19728]
[    0     1     2 ... 21155 21156 21157] [19729]
[    0     1     2 ... 21155 21156 21157] [19730]
[    0     1     2 ... 21155 21156 21157] [19731]


[    0     1     2 ... 21155 21156 21157] [19923]
[    0     1     2 ... 21155 21156 21157] [19924]
[    0     1     2 ... 21155 21156 21157] [19925]
[    0     1     2 ... 21155 21156 21157] [19926]
[    0     1     2 ... 21155 21156 21157] [19927]
[    0     1     2 ... 21155 21156 21157] [19928]
[    0     1     2 ... 21155 21156 21157] [19929]
[    0     1     2 ... 21155 21156 21157] [19930]
[    0     1     2 ... 21155 21156 21157] [19931]
[    0     1     2 ... 21155 21156 21157] [19932]
[    0     1     2 ... 21155 21156 21157] [19933]
[    0     1     2 ... 21155 21156 21157] [19934]
[    0     1     2 ... 21155 21156 21157] [19935]
[    0     1     2 ... 21155 21156 21157] [19936]
[    0     1     2 ... 21155 21156 21157] [19937]
[    0     1     2 ... 21155 21156 21157] [19938]
[    0     1     2 ... 21155 21156 21157] [19939]
[    0     1     2 ... 21155 21156 21157] [19940]
[    0     1     2 ... 21155 21156 21157] [19941]
[    0     1     2 ... 21155 21156 21157] [19942]


[    0     1     2 ... 21155 21156 21157] [20158]
[    0     1     2 ... 21155 21156 21157] [20159]
[    0     1     2 ... 21155 21156 21157] [20160]
[    0     1     2 ... 21155 21156 21157] [20161]
[    0     1     2 ... 21155 21156 21157] [20162]
[    0     1     2 ... 21155 21156 21157] [20163]
[    0     1     2 ... 21155 21156 21157] [20164]
[    0     1     2 ... 21155 21156 21157] [20165]
[    0     1     2 ... 21155 21156 21157] [20166]
[    0     1     2 ... 21155 21156 21157] [20167]
[    0     1     2 ... 21155 21156 21157] [20168]
[    0     1     2 ... 21155 21156 21157] [20169]
[    0     1     2 ... 21155 21156 21157] [20170]
[    0     1     2 ... 21155 21156 21157] [20171]
[    0     1     2 ... 21155 21156 21157] [20172]
[    0     1     2 ... 21155 21156 21157] [20173]
[    0     1     2 ... 21155 21156 21157] [20174]
[    0     1     2 ... 21155 21156 21157] [20175]
[    0     1     2 ... 21155 21156 21157] [20176]
[    0     1     2 ... 21155 21156 21157] [20177]


[    0     1     2 ... 21155 21156 21157] [20390]
[    0     1     2 ... 21155 21156 21157] [20391]
[    0     1     2 ... 21155 21156 21157] [20392]
[    0     1     2 ... 21155 21156 21157] [20393]
[    0     1     2 ... 21155 21156 21157] [20394]
[    0     1     2 ... 21155 21156 21157] [20395]
[    0     1     2 ... 21155 21156 21157] [20396]
[    0     1     2 ... 21155 21156 21157] [20397]
[    0     1     2 ... 21155 21156 21157] [20398]
[    0     1     2 ... 21155 21156 21157] [20399]
[    0     1     2 ... 21155 21156 21157] [20400]
[    0     1     2 ... 21155 21156 21157] [20401]
[    0     1     2 ... 21155 21156 21157] [20402]
[    0     1     2 ... 21155 21156 21157] [20403]
[    0     1     2 ... 21155 21156 21157] [20404]
[    0     1     2 ... 21155 21156 21157] [20405]
[    0     1     2 ... 21155 21156 21157] [20406]
[    0     1     2 ... 21155 21156 21157] [20407]
[    0     1     2 ... 21155 21156 21157] [20408]
[    0     1     2 ... 21155 21156 21157] [20409]


[    0     1     2 ... 21155 21156 21157] [20663]
[    0     1     2 ... 21155 21156 21157] [20664]
[    0     1     2 ... 21155 21156 21157] [20665]
[    0     1     2 ... 21155 21156 21157] [20666]
[    0     1     2 ... 21155 21156 21157] [20667]
[    0     1     2 ... 21155 21156 21157] [20668]
[    0     1     2 ... 21155 21156 21157] [20669]
[    0     1     2 ... 21155 21156 21157] [20670]
[    0     1     2 ... 21155 21156 21157] [20671]
[    0     1     2 ... 21155 21156 21157] [20672]
[    0     1     2 ... 21155 21156 21157] [20673]
[    0     1     2 ... 21155 21156 21157] [20674]
[    0     1     2 ... 21155 21156 21157] [20675]
[    0     1     2 ... 21155 21156 21157] [20676]
[    0     1     2 ... 21155 21156 21157] [20677]
[    0     1     2 ... 21155 21156 21157] [20678]
[    0     1     2 ... 21155 21156 21157] [20679]
[    0     1     2 ... 21155 21156 21157] [20680]
[    0     1     2 ... 21155 21156 21157] [20681]
[    0     1     2 ... 21155 21156 21157] [20682]


[    0     1     2 ... 21155 21156 21157] [20927]
[    0     1     2 ... 21155 21156 21157] [20928]
[    0     1     2 ... 21155 21156 21157] [20929]
[    0     1     2 ... 21155 21156 21157] [20930]
[    0     1     2 ... 21155 21156 21157] [20931]
[    0     1     2 ... 21155 21156 21157] [20932]
[    0     1     2 ... 21155 21156 21157] [20933]
[    0     1     2 ... 21155 21156 21157] [20934]
[    0     1     2 ... 21155 21156 21157] [20935]
[    0     1     2 ... 21155 21156 21157] [20936]
[    0     1     2 ... 21155 21156 21157] [20937]
[    0     1     2 ... 21155 21156 21157] [20938]
[    0     1     2 ... 21155 21156 21157] [20939]
[    0     1     2 ... 21155 21156 21157] [20940]
[    0     1     2 ... 21155 21156 21157] [20941]
[    0     1     2 ... 21155 21156 21157] [20942]
[    0     1     2 ... 21155 21156 21157] [20943]
[    0     1     2 ... 21155 21156 21157] [20944]
[    0     1     2 ... 21155 21156 21157] [20945]
[    0     1     2 ... 21155 21156 21157] [20946]
